Repository MicrosoftDocs/cpp-docs, pull requests merged in 2018-10, with the labels that each got.

#449 Update how-to-report-a-problem-with-the-visual-cpp-toolset.md
  docs/how-to-report-a-problem-with-the-visual-cpp-toolset.md
Labels: Change sent to author, do-not-merge

#455 Changed "top end of the stack" to top of the stack in line 199
  docs/standard-library/stack-class.md
Labels: Change sent to author, ready-to-merge

#452 Fix indent on lvalues and rvalues code sample
  docs/cpp/lvalues-and-rvalues-visual-cpp.md
Labels: Change sent to author, do-not-merge

#456 typo: widows -> windows
  docs/mfc/what-frame-windows-do.md
Labels: Change sent to author, do-not-merge

#457 typo: widows -> windows
  docs/mfc/frame-windows.md
Labels: Change sent to author, do-not-merge

#454 There is no '&&=' operator
  docs/cpp/assignment-operators.md
Labels: Change sent to author, do-not-merge

#462 Setup Addition for Fedora distribution
  docs/linux/download-install-and-setup-the-linux-development-workload.md
Labels: Change sent to author, do-not-merge

#469 Typo in lroundl example results
  docs/c-runtime-library/reference/lround-lroundf-lroundl-llround-llroundf-llroundl.md
Labels: Change sent to author, do-not-merge

#464 Fix typo in VectorIterator::operator +
  docs/cppcx/platform-collections-vectoriterator-class.md
Labels: Change sent to author, do-not-merge

#465 minor typo mistake
  docs/windows/overview-of-windows-programming-in-cpp.md
Labels: Change sent to author, do-not-merge

#474 Update initializing-classes-and-structs-without-constructors-cpp.md
  docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md
Labels: Change sent to author, do-not-merge

#481 Fix formatting in C constants sections
  docs/c-language/c-constants.md
  docs/c-language/c-floating-point-constants.md
  docs/c-language/c-string-literals.md
  docs/c-language/elements-of-c.md
Labels: Change sent to author, do-not-merge

#467 Expanded proto.md
  docs/assembler/masm/proto.md
Labels: Change sent to author, do-not-merge

#487 Update proto.md
  docs/assembler/masm/proto.md
Labels: do-not-merge

#491 CC76665: Tab and style issue
  docs/c-runtime-library/stdin-stdout-stderr.md
Labels: Change sent to author, ready-to-merge

#494 remove implicit reference to Intel 286
  docs/build/reference/oy-frame-pointer-omission.md
Labels: Change sent to author, do-not-merge

#492 Update abort-function-c.md
  docs/c-language/abort-function-c.md
Labels: Change sent to author, do-not-merge

#488 Update bss-seg.md for #486
  docs/preprocessor/bss-seg.md
Labels: do-not-merge

#485 Update data-seg.md
  docs/preprocessor/data-seg.md
Labels: do-not-merge

#498 Add exe_initialize_mta.lib to linkopt page.
  docs/c-runtime-library/link-options.md
Labels: Change sent to author, do-not-merge

#504 typo: Double word "is"
  docs/build/reference/std-specify-language-standard-version.md
Labels: Change sent to author, do-not-merge

#505 chore: Remove en-us from docs.microsoft.com links
  CONTRIBUTING.md
  styleguide/template.md
Labels: do-not-merge

#503 typo: Double word "the"
  docs/error-messages/compiler-errors-2/compiler-error-c2872.md
Labels: Change sent to author, do-not-merge

#502 typo: Double word "about"
  docs/ide/ide-and-tools-for-visual-cpp-development.md
Labels: Change sent to author, do-not-merge

#501 typo: Double word "function"
  docs/ide/refactoring/extract-function.md
Labels: Change sent to author, do-not-merge

#500 typo: supress -> suppress
  .openpublishing.redirection.json
  docs/build/reference/TOC.md
  docs/build/reference/clrunmanagedcodecheck-add-suppressunmanagedcodesecurityattribute.md
  docs/build/reference/linker-options.md
  docs/ide/xml-data-generator-tool-property-page.md
  docs/porting/visual-cpp-what-s-new-2003-through-2015.md
  docs/windows/use-winmdidl-and-midlrt-to-create-h-files-from-windows-metadata.md
Labels: Change sent to author, do-not-merge

#499 typo: Double word "in"
  docs/porting/porting-guide-spy-increment.md
Labels: Change sent to author, do-not-merge

#507 typo: foward -> forward
  docs/mfc/reference/crecordset-class.md
Labels: Change sent to author, do-not-merge

#508 Fixed typos
  docs/cpp/auto-cpp.md
Labels: Change sent to author, do-not-merge

#509 typo: futher -> further
  docs/cpp/scope-visual-cpp.md
Labels: Change sent to author, do-not-merge

#510 typo: noticable -> noticeable
  docs/mfc/codesnippet/CPP/cdc-class_12.cpp
Labels: Change sent to author, do-not-merge

#512 typo: supercede -> supersede
  docs/cpp-conformance-improvements-2017.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4996.md
  docs/mfc/active-technology-on-the-internet.md
  docs/mfc/activex-control-containers-handling-events-from-an-activex-control.md
  docs/mfc/activex-control-containers-manually-enabling-activex-control-containment.md
  docs/mfc/containers-for-activex-controls.md
  docs/mfc/internet-information-by-task.md
  docs/mfc/mfc-activex-controls-adding-custom-methods.md
  docs/mfc/mfc-activex-controls-adding-stock-methods.md
  docs/mfc/mfc-activex-controls-advanced-property-implementation.md
  docs/mfc/mfc-activex-controls-advanced-topics.md
  docs/mfc/mfc-activex-controls-distributing-activex-controls.md
  docs/mfc/mfc-activex-controls-licensing-an-activex-control.md
  docs/mfc/mfc-activex-controls-localizing-an-activex-control.md
  docs/mfc/mfc-activex-controls-optimization.md
  docs/mfc/mfc-activex-controls-painting-an-activex-control.md
  docs/mfc/mfc-activex-controls-property-pages.md
  docs/mfc/mfc-activex-controls-serializing.md
  docs/mfc/mfc-activex-controls-subclassing-a-windows-control.md
  docs/mfc/mfc-activex-controls-using-data-binding-in-an-activex-control.md
  docs/mfc/mfc-activex-controls-using-stock-property-pages.md
  docs/mfc/programming-activex-controls-in-a-activex-control-container.md
  docs/mfc/reference/cprintdialog-class.md
  docs/mfc/reference/creating-an-mfc-activex-control-container.md
  docs/mfc/reference/mfc-activex-control-wizard.md
  docs/mfc/upgrading-an-existing-activex-control.md
  docs/mfc/win32-internet-classes.md
  docs/text/mbcs-programming-tips.md
  docs/windows/windows-runtime-cpp-template-library-wrl.md
Labels: Change sent to author, do-not-merge

#513 typo: refered -> referred
  docs/windows/handle-to-object-operator-hat-cpp-component-extensions.md
Labels: Change sent to author, do-not-merge
