Repository MicrosoftDocs/cpp-docs, pull requests merged in 2019-05, with the labels that each got.

#982 OLE DB has been undeprecated
  docs/data/atl-database-classes-ole-db-templates.md
Labels: Change sent to author, do-not-merge, triaged

#981 Extra warning text about thread handle lifetime
  docs/mfc/reference/cwinthread-class.md
Labels: Change sent to author, do-not-merge, triaged

#983 OLE DB has been undeprecated
  docs/data/oledb/ole-db-programming.md
Labels: Change sent to author, do-not-merge

#984 Updating OLE DB and ODBC references
  docs/data/data-access-in-cpp.md
Labels: Change sent to author, do-not-merge

#985 ODBC and OLE DB reference updates
  docs/data/data-access-programming-mfc-atl.md
Labels: Change sent to author, do-not-merge

#995 Add ARM64 as supported platform
  docs/intrinsics/debugbreak.md
Labels: Change sent to author, do-not-merge

#999 Fix git push error for protected CLA branch
  docs/atl/adding-a-property-page-atl-tutorial-part-6.md
  docs/atl/example-implementing-a-property-page.md
  docs/atl/implementing-property-pages.md
  docs/atl/reference/adding-an-atl-ole-db-consumer.md
  docs/atl/reference/adding-an-atl-ole-db-provider.md
  docs/atl/reference/adding-an-atl-property-page.md
  docs/atl/reference/atl-active-server-page-component-wizard.md
  docs/atl/reference/atl-com-plus-1-0-component-wizard.md
  docs/atl/reference/atl-ole-db-consumer-wizard.md
  docs/atl/reference/atl-ole-db-provider-wizard.md
  docs/atl/reference/atl-property-page-wizard.md
  docs/atl/reference/options-atl-property-page-wizard.md
  docs/atl/reference/strings-atl-property-page-wizard.md
  docs/data/oledb/adding-an-interface-to-your-provider.md
  docs/data/oledb/consumer-wizard-generated-classes.md
  docs/data/oledb/consumer-wizard-generated-methods.md
  docs/data/oledb/creating-a-consumer-without-using-a-wizard.md
  docs/data/oledb/creating-a-simple-consumer.md
  docs/data/oledb/creating-a-simple-read-only-provider.md
  docs/data/oledb/creating-an-ole-db-consumer-using-a-wizard.md
  docs/data/oledb/creating-an-ole-db-consumer.md
  docs/data/oledb/creating-the-provider.md
  docs/data/oledb/determining-which-type-of-accessor-to-use.md
  docs/data/oledb/field-status-data-members-in-wizard-generated-accessors.md
  docs/data/oledb/implementing-a-simple-consumer.md
  docs/data/oledb/ole-db-architectural-design-issues.md
  docs/data/oledb/ole-db-templates.md
  docs/data/oledb/provider-wizard-generated-files.md
  docs/data/oledb/storing-strings-in-the-ole-db-provider.md
  docs/data/oledb/supporting-schema-rowsets.md
  docs/data/oledb/updating-rowsets.md
  docs/data/oledb/user-record.md
  docs/data/oledb/user-records.md
  docs/ide/adding-functionality-with-code-wizards-cpp.md
  docs/mfc/mfc-and-atl.md
  docs/mfc/mfc-library-versions.md
  docs/mfc/mfc-mbcs-dll-add-on.md
  docs/mfc/reference/add-class-from-typelib-wizard.md
  docs/mfc/reference/database-support-mfc-application-wizard.md
  docs/mfc/reference/mfc-odbc-consumer-wizard.md
  docs/parallel/amp/reference/accelerator-view-class.md
  docs/parallel/amp/reference/accelerator-view-removed-class.md
  docs/parallel/amp/reference/unsupported-feature-class.md
  docs/parallel/openmp/3-run-time-library-functions.md
Labels: Change sent to author

#1011 Fix git push error for protected CLA branch
  docs/build/cmake-predefined-configuration-reference.md
  docs/cloud/cloud-and-web-programming-in-visual-cpp.md
  docs/extensions/classes-and-structs-cpp-component-extensions.md
  docs/index.md
Labels: Change sent to author, do-not-merge

#1013 Fix git push error for protected CLA branch
  docs/_breadcrumb/toc.yml
  docs/atl/TOC.md
  docs/atl/active-template-library-atl-concepts.md
  docs/atl/reference/TOC.md
  docs/atl/toc.yml
  docs/build/building-on-the-command-line.md
  docs/build/cmakesettings-reference.md
  docs/build/configuring-programs-for-windows-xp.md
  docs/build/cppproperties-schema-reference.md
  docs/build/creating-and-managing-visual-cpp-projects.md
  docs/build/customize-cmake-settings.md
  docs/build/how-to-enable-a-64-bit-visual-cpp-toolset-on-the-command-line.md
  docs/build/how-to-integrate-custom-tools-into-the-project-properties.md
  docs/build/project-property-inheritance.md
  docs/build/reference/clr-common-language-runtime-compilation.md
  docs/build/reference/clr-restrictions.md
  docs/build/reference/clrheader.md
  docs/build/reference/clrimagetype-specify-type-of-clr-image.md
  docs/build/reference/clrunmanagedcodecheck-add-suppressunmanagedcodesecurityattribute.md
  docs/build/reference/creating-a-makefile-project.md
  docs/build/reference/debug-generate-debug-info.md
  docs/build/reference/gd-gr-gv-gz-calling-convention.md
  docs/build/reference/ltcg-link-time-code-generation.md
  docs/build/reference/msbuild-visual-cpp-overview.md
  docs/build/reference/netmodule-files-as-linker-input.md
  docs/build/reference/property-page-xml-files.md
  docs/build/reference/qspectre.md
  docs/build/reference/std-specify-language-standard-version.md
  docs/build/reference/vcxproj-file-structure.md
  docs/build/reference/zc-cplusplus.md
  docs/build/vcpkg.md
  docs/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project.md
  docs/porting/features-deprecated-in-visual-studio.md
  docs/windows/TOC.md
  docs/windows/overview-of-windows-programming-in-cpp.md
Labels: Change sent to author

#1017 Update http links
  docs/assembler/masm/dot-model.md
  docs/assembler/masm/ml-fatal-error-a1016.md
Labels: Change sent to author, do-not-merge

#1016 Update http links
  README.md
Labels: Change sent to author, do-not-merge

#1018 Fix git push error for protected CLA branch
  docs/build/reference/zc-alignednew.md
  docs/cpp/trivial-standard-layout-and-pod-types.md
  docs/overview/2017/cpp-conformance-improvements-2017.md
  docs/overview/2017/what-s-new-for-visual-cpp-in-visual-studio.md
  docs/overview/2019/cpp-conformance-improvements-2019.md
  docs/overview/2019/what-s-new-for-visual-cpp-in-visual-studio.md
  docs/overview/visual-cpp-in-visual-studio.md
  docs/overview/visual-cpp-language-conformance.md
Labels: Change sent to author, cpp-language/tech, do-not-merge

#1021 Fix git push error for protected CLA branch
  docs/mfc/reference/message-map-macros-mfc.md
  docs/mfc/reference/run-time-object-model-services.md
  docs/overview/visual-cpp-language-conformance.md
  docs/parallel/amp/reference/runtime-exception-class.md
  docs/parallel/amp/reference/tile-barrier-class.md
  docs/parallel/amp/reference/uninitialized-object-class.md
  docs/parallel/concrt/reference/task-handle-class.md
Labels: Change sent to author, cpp-language/tech, do-not-merge

#1032 Fix git push error for protected CLA branch
  docs/assembler/masm/dot-errdif.md
  docs/assembler/masm/dot-erridn.md
  docs/assembler/masm/ifdif.md
  docs/assembler/masm/ifidn.md
  docs/assembler/masm/ml-nonfatal-error-a2219.md
  docs/docfx.json
  docs/mfc/TOC.md
  docs/mfc/reference/TOC.md
  docs/mfc/toc.yml
  docs/windows/TOC.md
  docs/windows/overview-of-windows-programming-in-cpp.md
Labels: Change sent to author, do-not-merge

#1033 Add "topictype" metadata per 21703909.
  docs/c-runtime-library/reference/memcmp-wmemcmp.md
Labels: Change sent to author, do-not-merge

#1041 Update gf-eliminate-duplicate-strings.md
  docs/build/reference/gf-eliminate-duplicate-strings.md
Labels: Change sent to author, do-not-merge

#1034 Update gd-gr-gv-gz-calling-convention.md
  docs/build/reference/gd-gr-gv-gz-calling-convention.md
Labels: Change sent to author, do-not-merge

#1037 Update http links
  docs/atl/reference/atl-http-utility-functions.md
  docs/atl/reference/atl-text-encoding-functions.md
Labels: Change sent to author, do-not-merge

#1038 Update http links
  docs/build/configuring-programs-for-windows-xp.md
  docs/build/how-to-modify-the-target-framework-and-platform-toolset.md
  docs/build/reference/dot-obj-files-as-linker-input.md
  docs/build/reference/gw-optimize-global-data.md
  docs/build/reference/integritycheck-require-signature-check.md
  docs/build/reference/subsystem.md
  docs/build/reference/vcpp-directories-property-page.md
  docs/build/reference/winmd-generate-windows-metadata.md
Labels: Change sent to author, do-not-merge

#1039 Update http links
  docs/cpp/alignment-cpp-declarations.md
  docs/cpp/constructors-cpp.md
  docs/cpp/identifiers-cpp.md
  docs/cpp/string-and-i-o-formatting-modern-cpp.md
Labels: Change sent to author, do-not-merge

#1040 Update http links
  docs/cppcx/wrl/walkthrough-creating-a-windows-store-app-using-wrl-and-media-foundation.md
Labels: Change sent to author, do-not-merge

#1042 Fix git push error for protected CLA branch
  README.md
  docs/linux/TOC.md
  docs/linux/toc.yml
Labels: Change sent to author

#1043 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/TOC.md
  docs/_breadcrumb/toc.yml
  docs/assembler/arm/TOC.md
  docs/assembler/inline/TOC.md
  docs/assembler/masm/TOC.md
  docs/assembler/masm/ml-error-messages.md
  docs/assembler/masm/ml-fatal-errors.md
  docs/assembler/masm/ml-nonfatal-errors-a2000-a2049.md
  docs/assembler/masm/ml-nonfatal-errors-a2050-a2099.md
  docs/assembler/masm/ml-nonfatal-errors-a2100-a2149.md
  docs/assembler/masm/ml-nonfatal-errors-a2150-a2199.md
  docs/assembler/masm/ml-nonfatal-errors-a2200-a2901.md
  docs/assembler/masm/ml-nonfatal-errors.md
  docs/assembler/masm/ml-warnings.md
  docs/assembler/masm/operators-masm.md
  docs/assembler/masm/run-time-operators.md
  docs/atl-mfc-shared/TOC.md
  docs/build/TOC.md
  docs/build/reference/TOC.md
  docs/c-language/TOC.md
  docs/c-runtime-library/TOC.md
  docs/c-runtime-library/reference/TOC.md
  docs/cpp/TOC.md
  docs/cppcx/TOC.md
  docs/data/TOC.md
  docs/data/odbc/TOC.md
  docs/data/oledb/TOC.md
  docs/dotnet/TOC.md
  docs/error-messages/toc.yml
  docs/extensions/TOC.md
  docs/ide/TOC.md
  docs/intrinsics/TOC.md
  docs/parallel/TOC.md
  docs/parallel/amp/TOC.md
  docs/parallel/amp/reference/TOC.md
  docs/parallel/concrt/TOC.md
  docs/parallel/concrt/reference/TOC.md
  docs/parallel/openmp/TOC.md
  docs/porting/TOC.md
  docs/preprocessor/TOC.md
  docs/standard-library/TOC.md
  docs/text/TOC.md
  docs/toc.yml
  docs/windows/TOC.md
  docs/windows/attributes/TOC.md
  docs/windows/overview-of-windows-programming-in-cpp.md
Labels: Change sent to author

#1046 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/get-started/2017/tutorial-console-cpp.md
  docs/get-started/2019/tutorial-console-cpp.md
  docs/get-started/index.yml
  docs/get-started/media/calc-vs2019-build-your-project.png
  docs/get-started/media/calc-vs2019-choose-console-app.png
  docs/get-started/media/calc-vs2019-conditional-breakpoint.png
  docs/get-started/media/calc-vs2019-create-calculator-class.png
  docs/get-started/media/calc-vs2019-create-definition.png
  docs/get-started/media/calc-vs2019-debug-breakpoint.png
  docs/get-started/media/calc-vs2019-debug-locals.png
  docs/get-started/media/calc-vs2019-divide-by-zero-fail.png
  docs/get-started/media/calc-vs2019-final-verification.png
  docs/get-started/media/calc-vs2019-five-plus-five.png
  docs/get-started/media/calc-vs2019-hello-world-console.png
  docs/get-started/media/calc-vs2019-hover-tooltip.png
  docs/get-started/media/calc-vs2019-initial-dialog.png
  docs/get-started/media/calc-vs2019-name-your-project.png
  docs/get-started/media/calc-vs2019-pop-up-definition.png
  docs/get-started/media/calc-vs2019-set-breakpoint.png
  docs/get-started/media/calc-vs2019-solution-explorer.png
  docs/get-started/media/calculator-app.gif
  docs/get-started/media/calculator-autos.png
  docs/get-started/media/calculator-conditional-breakpoint.gif
  docs/get-started/media/calculator-create-class.gif
  docs/get-started/media/calculator-create-definition.gif
  docs/get-started/media/calculator-debug-conditional.gif
  docs/get-started/media/calculator-divide-by-zero-fail.png
  docs/get-started/media/calculator-final-verification.gif
  docs/get-started/media/calculator-first-launch.gif
  docs/get-started/media/calculator-five-plus-five.png
  docs/get-started/media/calculator-hello-world-console.png
  docs/get-started/media/calculator-hover-tooltip.gif
  docs/get-started/media/calculator-initial-build-output.png
  docs/get-started/media/calculator-locals.png
  docs/get-started/media/calculator-new-project-dialog.gif
  docs/get-started/media/calculator-new-project-dialog.png
  docs/get-started/media/calculator-set-breakpoint.gif
  docs/get-started/media/calculator-solution-explorer.png
  docs/get-started/media/calculator-undefined-zero.gif
  docs/get-started/media/cpp-test-explorer-passed.1.png
  docs/get-started/media/cpp-test-explorer-passed.png
  docs/get-started/media/vs2017-debug-watch.png
  docs/get-started/media/vs2017-new-project.png
  docs/get-started/media/vs2017-output-error-list.png
  docs/get-started/media/vs2017-solution-explorer-code-editor.png
  docs/get-started/media/vs2017-team-explorer.png
  docs/get-started/media/vs2017-toolbox-designer.png
  docs/get-started/toc.yml
  docs/get-started/tutorial-console-cpp.md
Labels: Change sent to author, do-not-merge

#1045 Update http links
  docs/dotnet/hosting-a-windows-form-user-control-as-an-mfc-dialog-box.md
  docs/dotnet/hosting-a-windows-form-user-control-in-an-mfc-dialog-box.md
  docs/dotnet/hosting-a-windows-forms-user-control-as-an-mfc-view.md
  docs/dotnet/windows-forms-mfc-programming-differences.md
Labels: do-not-merge
