Repository MicrosoftDocs/cpp-docs, pull requests merged in 2019-11, with the labels that each got.

#1680 Fix typo
  docs/build/reference/zc-noexcepttypes.md
  docs/cpp/constructors-cpp.md
  docs/windows/walkthrough-creating-a-standard-cpp-program-cpp.md
Labels: Change sent to author, do-not-merge

#1681 Update max-none-class.md
  docs/standard-library/max-none-class.md
Labels: Change sent to author, do-not-merge

#1688 Fix git push error for protected CLA branch
  docs/assembler/masm/assume.md
  docs/assembler/masm/dosseg.md
  docs/assembler/masm/dot-386.md
  docs/assembler/masm/dot-386p.md
  docs/assembler/masm/dot-387.md
  docs/assembler/masm/dot-486.md
  docs/assembler/masm/dot-486p.md
  docs/assembler/masm/dot-586.md
  docs/assembler/masm/dot-586p.md
  docs/assembler/masm/dot-686.md
  docs/assembler/masm/dot-686p.md
  docs/assembler/masm/dot-alpha.md
  docs/assembler/masm/dot-break.md
  docs/assembler/masm/dot-continue.md
  docs/assembler/masm/dot-dosseg.md
  docs/assembler/masm/dot-else.md
  docs/assembler/masm/dot-endif.md
  docs/assembler/masm/dot-endw.md
  docs/assembler/masm/dot-exit.md
  docs/assembler/masm/dot-fardata-q.md
  docs/assembler/masm/dot-fardata.md
  docs/assembler/masm/dot-fpo.md
  docs/assembler/masm/dot-if.md
  docs/assembler/masm/dot-k3d.md
  docs/assembler/masm/dot-mmx.md
  docs/assembler/masm/dot-model.md
  docs/assembler/masm/dot-repeat.md
  docs/assembler/masm/dot-safeseh.md
  docs/assembler/masm/dot-seq.md
  docs/assembler/masm/dot-stack.md
  docs/assembler/masm/dot-startup.md
  docs/assembler/masm/dot-until.md
  docs/assembler/masm/dot-untilcxz.md
  docs/assembler/masm/dot-while.md
  docs/assembler/masm/dot-xmm.md
  docs/assembler/masm/group.md
  docs/assembler/masm/invoke.md
  docs/dotnet/hosting-a-windows-form-user-control-as-an-mfc-dialog-box.md
  docs/dotnet/hosting-a-windows-form-user-control-in-an-mfc-dialog-box.md
  docs/dotnet/hosting-a-windows-forms-user-control-as-an-mfc-view.md
  docs/dotnet/windows-forms-mfc-programming-differences.md
Labels: do-not-merge

#1685 Update basic_string::data() documentation
  docs/standard-library/basic-string-class.md
Labels: Change sent to author, assessing_(C&L), cpp-standard-libraries/tech, do-not-merge, visual-cpp/prod

#1689 Fix git push error for protected CLA branch
  docs/build/reference/experimental-preprocessor.md
  docs/overview/visual-cpp-language-conformance.md
  docs/overview/what-s-new-for-visual-cpp-in-visual-studio.md
  docs/preprocessor/c-cpp-preprocessor-reference.md
  docs/preprocessor/preprocessor-experimental-overview.md
  docs/toc.yml
Labels: do-not-merge

#1692 Link to WSL offline download instructions
  docs/linux/download-install-and-setup-the-linux-development-workload.md
Labels: Change sent to author, cpp-linux/tech, do-not-merge, visual-cpp/prod

#1694 Update algorithm.md
  docs/standard-library/algorithm.md
Labels: Change sent to author, cpp-standard-libraries/tech, do-not-merge, visual-cpp/prod

#1699 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4311.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4312.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4313.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4329.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4333.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4346.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4348.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4353.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4358.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4364.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4369.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4374.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4376.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4377.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4378.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4383.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4384.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4391.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4392.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4393.md
Labels: Change sent to author, assessing_(C&L), cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1700 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4395.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4397.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4401.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4405.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4407.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4440.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4441.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4461.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4470.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4486.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4488.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4489.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4490.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4508.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4518.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4526.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4530.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4532.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4533.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4540.md
Labels: Change sent to author, assessing_(C&L), cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1701 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4544.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4545.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4546.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4547.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4548.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4549.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4550.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4551.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4552.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4553.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4555.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4558.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4561.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4566.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4572.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4581.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4584.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4600.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4602.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4606.md
Labels: Change sent to author, assessing_(C&L), cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1707 Fix git push error for protected CLA branch
  docs/build/get-started-linux-cmake.md
  docs/build/how-to-modify-the-target-framework-and-platform-toolset.md
  docs/c-language/pragmas.md
  docs/dotnet/hosting-a-windows-form-user-control-as-an-mfc-dialog-box.md
  docs/dotnet/hosting-a-windows-form-user-control-in-an-mfc-dialog-box.md
  docs/dotnet/hosting-a-windows-forms-user-control-as-an-mfc-view.md
  docs/dotnet/windows-forms-mfc-programming-differences.md
  docs/linux/connect-to-your-remote-linux-computer.md
  docs/linux/download-install-and-setup-the-linux-development-workload.md
  docs/porting/binary-compat-2015-2017.md
  docs/preprocessor/pack.md
  docs/windows/redistributing-the-mfc-library.md
Labels: do-not-merge

#1706 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4715.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4716.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4717.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4722.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4730.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4731.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4733.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4739.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4742.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4744.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4747.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4750.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4788.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4794.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4803.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4804.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4805.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4806.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4807.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4810.md
Labels: Change sent to author, assessing_(C&L), cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1705 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4615.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4616.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4618.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4620.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4621.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4624.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4628.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4630.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4632.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4659.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4661.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4662.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4667.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4669.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4674.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4677.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4684.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4688.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4691.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4692.md
Labels: Change sent to author, assessing_(C&L), cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1711 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4946.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4964.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4965.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4997.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4056.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4094.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4099.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4146.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4150.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4156.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4244.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4250.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4285.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4302.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4307.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4308.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4309.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4356.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4396.md
  docs/error-messages/compiler-warnings/compiler-warning-level-2-c4756.md
Labels: Change sent to author, cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1710 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4812.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4813.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4817.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4822.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4829.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4835.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4838.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4905.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4906.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4912.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4920.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4925.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4926.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4927.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4928.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4929.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4930.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4939.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4944.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4945.md
Labels: Change sent to author, cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1712 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4018.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4073.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4101.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4102.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4191.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4197.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4240.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4243.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4265.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4267.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4280.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4281.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4287.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4290.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4310.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4334.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4357.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4359.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4390.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4414.md
Labels: Change sent to author, cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1720 Fix experimental:preprocessor links
  docs/preprocessor/predefined-macros.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#1718 Fix git push error for protected CLA branch
  docs/porting/ide-tools-for-upgrading-code.md
  docs/porting/media/code-analysis-error-list.png
  docs/porting/media/code-analysis-filter.png
  docs/porting/media/code-analysis-tooltip.png
  docs/porting/media/compiler-error-list.png
  docs/porting/media/conformance-prop-page.png
  docs/porting/media/constexpr-function-call.png
  docs/porting/media/constexpr-function.png
  docs/porting/media/document-health-indicator.png
  docs/porting/media/go-to-all.png
  docs/porting/media/init-variable.png
  docs/porting/media/macro-expansion-quick-info.png
  docs/porting/media/quick-action-macro-to-constexpr.png
  docs/porting/media/raw-string-literal.png
  docs/porting/media/upgrade-dialog-v142.png
  docs/porting/visual-cpp-porting-and-upgrading-guide.md
  docs/toc.yml
Labels: do-not-merge

#1723 ARM64 Windows does support Aarch32 UWAs
  docs/build/arm64-windows-abi-conventions.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#1726 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4521.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4522.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4534.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4535.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4538.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4554.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4557.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4570.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4608.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4619.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4633.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4635.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4636.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4637.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4640.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4641.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4645.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4646.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4738.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4792.md
Labels: Change sent to author, cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1725 Update Visual Studio version
  docs/build/reference/hint-files.md
Labels: Change sent to author, assessing_(C&L), cpp-tools/tech, do-not-merge, visual-cpp/prod

#1739 small grammatical fix
  docs/text/locales-and-code-pages.md
Labels: Change sent to author, cpp-windows/tech, do-not-merge, visual-cpp/prod

#1740 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4823.md
  docs/error-messages/compiler-warnings/compiler-warning-level-3-c4995.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4001.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4019.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4032.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4100.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4121.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4125.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4130.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4131.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4189.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4201.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4202.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4204.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4205.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4207.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4208.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4210.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4211.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4212.md
Labels: Change sent to author, assessing_(C&L), cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1741 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4213.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4214.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4220.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4221.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4232.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4234.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4235.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4238.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4239.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4242.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4245.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4254.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4255.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4256.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4263.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4266.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4268.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4289.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4296.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4324.md
Labels: Change sent to author, assessing_(C&L), cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#1745 Update warning.md
  docs/preprocessor/warning.md
Labels: Change sent to author, assessing_(C&L), cpp-language/tech, do-not-merge, visual-cpp/prod

#1749 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4336.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4337.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4339.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4343.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4365.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4366.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4389.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4400.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4408.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4429.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4431.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4434.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4460.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4481.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4487.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4512.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4514.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4515.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4516.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4564.md
Labels: Change sent to author, cpp-diagnostics/tech, do-not-merge, visual-cpp/prod
