Repository MicrosoftDocs/cpp-docs, pull requests merged in 2019-04, with the labels that each got.

#901 Make it clear that wmemchr operates on characters, not bytes
  docs/c-runtime-library/reference/memchr-wmemchr.md
Labels: Change sent to author, do-not-merge

#908 Fix git push error for protected CLA branch
  .acrolinx-config.edn
  docs/docfx.json
  docs/get-started/2017/media/calculator-app.gif
  docs/get-started/2017/media/calculator-autos.png
  docs/get-started/2017/media/calculator-conditional-breakpoint.gif
  docs/get-started/2017/media/calculator-create-class.gif
  docs/get-started/2017/media/calculator-create-definition.gif
  docs/get-started/2017/media/calculator-debug-conditional.gif
  docs/get-started/2017/media/calculator-divide-by-zero-fail.png
  docs/get-started/2017/media/calculator-final-verification.gif
  docs/get-started/2017/media/calculator-first-launch.gif
  docs/get-started/2017/media/calculator-five-plus-five.png
  docs/get-started/2017/media/calculator-hello-world-console.png
  docs/get-started/2017/media/calculator-hover-tooltip.gif
  docs/get-started/2017/media/calculator-initial-build-output.png
  docs/get-started/2017/media/calculator-locals.png
  docs/get-started/2017/media/calculator-new-project-dialog.gif
  docs/get-started/2017/media/calculator-new-project-dialog.png
  docs/get-started/2017/media/calculator-set-breakpoint.gif
  docs/get-started/2017/media/calculator-solution-explorer.png
  docs/get-started/2017/media/calculator-undefined-zero.gif
  docs/get-started/2017/media/cpp-test-explorer-passed.png
  docs/get-started/2017/media/vs2017-debug-watch.png
  docs/get-started/2017/media/vs2017-new-project.png
  docs/get-started/2017/media/vs2017-output-error-list.png
  docs/get-started/2017/media/vs2017-solution-explorer-code-editor.png
  docs/get-started/2017/media/vs2017-team-explorer.png
  docs/get-started/2017/media/vs2017-toolbox-designer.png
  docs/get-started/2017/tutorial-console-cpp.md
  docs/get-started/2019/media/calc-vs2019-build-your-project.png
  docs/get-started/2019/media/calc-vs2019-choose-console-app.png
  docs/get-started/2019/media/calc-vs2019-conditional-breakpoint.png
  docs/get-started/2019/media/calc-vs2019-create-calculator-class.png
  docs/get-started/2019/media/calc-vs2019-create-definition.png
  docs/get-started/2019/media/calc-vs2019-debug-breakpoint.png
  docs/get-started/2019/media/calc-vs2019-debug-locals.png
  docs/get-started/2019/media/calc-vs2019-divide-by-zero-fail.png
  docs/get-started/2019/media/calc-vs2019-final-verification.png
  docs/get-started/2019/media/calc-vs2019-five-plus-five.png
  docs/get-started/2019/media/calc-vs2019-hello-world-console.png
  docs/get-started/2019/media/calc-vs2019-hover-tooltip.png
  docs/get-started/2019/media/calc-vs2019-initial-dialog.png
  docs/get-started/2019/media/calc-vs2019-name-your-project.png
  docs/get-started/2019/media/calc-vs2019-pop-up-definition.png
  docs/get-started/2019/media/calc-vs2019-set-breakpoint.png
  docs/get-started/2019/media/calc-vs2019-solution-explorer.png
  docs/get-started/2019/media/cpp-test-explorer-passed.png
  docs/get-started/2019/tutorial-console-cpp.md
  docs/get-started/tutorial-console-cpp.md
Labels: Change sent to author

#909 In the compressed format, H represents 8 registers of 8 bytes each.
  docs/build/arm64-exception-handling.md
Labels: Change sent to author, do-not-merge

#915 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/TOC.md
  docs/_breadcrumb/toc.yml
  docs/build/media/vs2019-choose-console-app.png
  docs/build/media/vs2019-configure-new-project-hello-world.png
  docs/build/media/vs2019-hello-world-code.png
  docs/build/reference/zc-twophase.md
  docs/build/vscpp-step-0-installation.md
  docs/build/vscpp-step-1-create.md
  docs/cpp/constructors-cpp.md
  docs/get-started/media/vs-installer-individual-components.png
  docs/get-started/media/vs-installer-installation-locations.png
  docs/get-started/media/vs-installer-language-packs.png
  docs/get-started/media/vs-installer-workloads.png
  docs/index.md
  docs/overview/2017/cpp-conformance-improvements-2017.md
  docs/overview/2017/media/CppCoreCheck.png
  docs/overview/2017/media/ErrorList1.png
  docs/overview/2017/media/ErrorList2.png
  docs/overview/2017/media/api-stats.png
  docs/overview/2017/media/cmake_cpp.png
  docs/overview/2017/media/cpp-test-explorer-passed.png
  docs/overview/2017/media/frame-analysis.png
  docs/overview/2017/media/frame-validation.png
  docs/overview/2017/media/gpu-usage.png
  docs/overview/2017/media/gpu-view.png
  docs/overview/2017/media/io-shaders.png
  docs/overview/2017/media/memory-stats.png
  docs/overview/2017/media/mlfiltering.png
  docs/overview/2017/media/resource-history-change.png
  docs/overview/2017/media/resource-history.png
  docs/overview/2017/media/search.png
  docs/overview/2017/media/vs2017-debug-watch.png
  docs/overview/2017/media/vs2017-new-project.png
  docs/overview/2017/media/vs2017-output-error-list.png
  docs/overview/2017/media/vs2017-solution-explorer-code-editor.png
  docs/overview/2017/media/vs2017-team-explorer.png
  docs/overview/2017/media/vs2017-toolbox-designer.png
  docs/overview/2017/what-s-new-for-visual-cpp-in-visual-studio.md
  docs/overview/2019/cpp-conformance-improvements-2019.md
  docs/overview/2019/what-s-new-for-visual-cpp-in-visual-studio.md
  docs/overview/cpp-conformance-improvements.md
  docs/overview/visual-cpp-in-visual-studio.md
  docs/overview/visual-cpp-language-conformance.md
  docs/overview/what-s-new-for-visual-cpp-in-visual-studio.md
  docs/porting/overview-of-potential-upgrade-issues-visual-cpp.md
  docs/porting/upgrade-your-code-to-the-universal-crt.md
  docs/porting/use-native-multi-targeting.md
  docs/porting/visual-cpp-change-history-2003-2015.md
  docs/porting/visual-cpp-porting-and-upgrading-guide.md
  docs/porting/visual-cpp-what-s-new-2003-through-2015.md
Labels: Change sent to author, cpp-language/tech, do-not-merge

#914 Cut unnecessary variables
  docs/cpp/template-specialization-cpp.md
Labels: Change sent to author, do-not-merge

#916 Add information on cwd
  docs/build/configure-cmake-debugging-sessions.md
Labels: Change sent to author, do-not-merge

#917 Array of unwind codes is described in section 3, not 4.
  docs/build/arm64-exception-handling.md
Labels: Change sent to author, do-not-merge

#918 After the xdata header, comes the epilog scope info. Fix confusion with "exception information", which comes last.
  docs/build/arm64-exception-handling.md
Labels: Change sent to author, do-not-merge

#922 Fix small 'm' -> ',' typo in compiler warning doc
  docs/build/reference/compiler-option-warning-level.md
Labels: Change sent to author, do-not-merge

#928 Clean up See also sections
  docs/build/open-folder-projects-cpp.md
  docs/cppcx/weak-references-and-breaking-cycles-c-cx.md
  docs/dotnet/native-and-dotnet-interoperability.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4211.md
Labels: Change sent to author, do-not-merge

#930 Fix git push error for protected CLA branch
  docs/build/reference/zp-struct-member-alignment.md
  docs/cpp/how-to-design-for-exception-safety.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4061.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4062.md
  docs/preprocessor/predefined-macros.md
Labels: Change sent to author, do-not-merge

#937 Fix git push error for protected CLA branch
  docs/error-messages/tool-errors/TOC.md
  docs/error-messages/tool-errors/linker-tools-errors-and-warnings.md
  docs/error-messages/tool-errors/linker-tools-warning-lnk4049.md
  docs/error-messages/tool-errors/linker-tools-warning-lnk4217.md
  docs/error-messages/tool-errors/linker-tools-warning-lnk4286.md
Labels: Change sent to author, do-not-merge

#938 Unwind codes are actually written to memory in big-endian form.
  docs/build/arm64-exception-handling.md
Labels: Change sent to author, do-not-merge

#941 Make code compile, function and actually follow the EABI
  docs/build/arm64-exception-handling.md
Labels: Change sent to author, do-not-merge

#939 Floats are indeed signed.
  docs/standard-library/is-signed-class.md
Labels: Change sent to author, do-not-merge

#950 Fix git push error for protected CLA branch
  docs/build/reference/openmp-enable-openmp-2-0-support.md
  docs/error-messages/tool-errors/linker-tools-warning-lnk4049.md
  docs/error-messages/tool-errors/linker-tools-warning-lnk4217.md
  docs/error-messages/tool-errors/linker-tools-warning-lnk4286.md
Labels: Change sent to author, do-not-merge

#956 Typo fix
  docs/build/projects-and-build-systems-cpp.md
Labels: Change sent to author, do-not-merge

#957 Correct description of isnormal
  docs/c-runtime-library/reference/isnormal.md
Labels: Change sent to author, do-not-merge

#953 Fix wcstombs_s and wcsrtombs_s pReturnValue parameter description
  docs/c-runtime-library/reference/wcsrtombs-s.md
  docs/c-runtime-library/reference/wcstombs-s-wcstombs-s-l.md
Labels: Change sent to author, do-not-merge

#958 Fix git push error for protected CLA branch
  docs/intrinsics/TOC.md
  docs/intrinsics/div128.md
  docs/intrinsics/div64.md
  docs/intrinsics/udiv128.md
  docs/intrinsics/udiv64.md
  docs/intrinsics/x64-amd64-intrinsics-list.md
  docs/intrinsics/x86-intrinsics-list.md
Labels: Change sent to author, do-not-merge

#780 Add docs for turn on /PROFILE linker option within CMake project
  docs/build/reference/profile-performance-tools-profiler.md
Labels: Change sent to author, do-not-merge

#838 Add "namespace" explanation for environments. Add "type" definition f…
  docs/ide/customize-cmake-settings.md
Labels: Change sent to author, do-not-merge

#964 Clarify UCRT Deployment
  docs/windows/universal-crt-deployment.md
Labels: Change sent to author, do-not-merge

#965 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/_breadcrumb/toc.yml
  docs/build/reference/TOC.md
  docs/error-messages/compiler-errors-1/TOC.md
  docs/error-messages/compiler-errors-1/c-cpp-build-errors.md
  docs/error-messages/compiler-errors-1/compiler-errors-c2000-c3999.md
  docs/error-messages/compiler-errors-1/compiler-errors-c2001-through-c2099.md
  docs/error-messages/compiler-errors-1/compiler-errors-c2100-through-c2199.md
  docs/error-messages/compiler-errors-1/compiler-errors-c2200-through-c2299.md
  docs/error-messages/compiler-errors-1/compiler-errors-c2300-through-c2399.md
  docs/error-messages/compiler-errors-1/compiler-errors-c2400-through-c2499.md
  docs/error-messages/compiler-errors-1/compiler-fatal-errors-c999-through-c1999.md
  docs/error-messages/compiler-errors-2/TOC.md
  docs/error-messages/compiler-errors-2/compiler-errors-c2500-through-c2599.md
  docs/error-messages/compiler-errors-2/compiler-errors-c2600-through-c2699.md
  docs/error-messages/compiler-errors-2/compiler-errors-c2700-through-c2799.md
  docs/error-messages/compiler-errors-2/compiler-errors-c2800-through-c2899.md
  docs/error-messages/compiler-errors-2/compiler-errors-c2900-through-c3499.md
  docs/error-messages/compiler-errors-2/compiler-errors-c3000-through-c3099.md
  docs/error-messages/compiler-errors-2/compiler-errors-c3100-through-c3199.md
  docs/error-messages/compiler-errors-2/compiler-errors-c3200-through-c3299.md
  docs/error-messages/compiler-errors-2/compiler-errors-c3300-through-c3399.md
  docs/error-messages/compiler-errors-2/compiler-errors-c3400-through-c3499.md
  docs/error-messages/compiler-errors-2/compiler-errors-c3500-through-c3999.md
  docs/error-messages/compiler-warnings/TOC.md
  docs/error-messages/compiler-warnings/compiler-warnings-by-compiler-version.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4000-c5999.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4000-through-c4199.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4200-through-c4399.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4400-through-c4599.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4600-through-c4799.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md
  docs/error-messages/includes/error-boilerplate.md
  docs/error-messages/toc.yml
  docs/error-messages/tool-errors/TOC.md
  docs/error-messages/tool-errors/automatic-function-scope-variables.md
  docs/error-messages/tool-errors/bscmake-errors-bk1500-through-bk4505.md
  docs/error-messages/tool-errors/c-runtime-errors-r6002-through-r6035.md
  docs/error-messages/tool-errors/command-line-errors-d8000-through-d9999.md
  docs/error-messages/tool-errors/cvtres-errors-cvt1100-through-cvt4001.md
  docs/error-messages/tool-errors/expression-evaluator-errors-cxx0000-through-cxx0072.md
  docs/error-messages/tool-errors/function-inlining-problems.md
  docs/error-messages/tool-errors/global-constants-in-cpp.md
  docs/error-messages/tool-errors/linker-tools-errors-and-warnings.md
  docs/error-messages/tool-errors/math-errors-m6101-through-m6205.md
  docs/error-messages/tool-errors/missing-function-body-or-variable.md
  docs/error-messages/tool-errors/name-decoration.md
  docs/error-messages/tool-errors/nmake-errors-u1000-through-u4011.md
  docs/error-messages/tool-errors/profile-guided-optimization-errors-and-warnings.md
  docs/error-messages/tool-errors/project-build-errors-and-warnings-prjxxxx.md
  docs/error-messages/tool-errors/resource-compiler-errors-rc1000-through-rc4413.md
  docs/error-messages/tool-errors/resource-compiler-errors-rw1004-through-rw4004.md
  docs/error-messages/tool-errors/vectorizer-and-parallelizer-messages.md
Labels: do-not-merge

#968 Default Alignment of Locals, Globals and Statics
  docs/build/arm64-windows-abi-conventions.md
Labels: Change sent to author, do-not-merge

#970 ARM64 ABI - HFA and HVA return values
  docs/build/arm64-windows-abi-conventions.md
Labels: Change sent to author, do-not-merge

#973 Fix git push error for protected CLA branch
  docs/cppcx/wrl/walkthrough-creating-a-windows-store-app-using-wrl-and-media-foundation.md
  docs/dotnet/walkthrough-compiling-a-cpp-program-that-targets-the-clr-in-visual-studio.md
  docs/mfc/walkthrough-adding-a-ctaskdialog-to-an-application.md
  docs/mfc/walkthrough-adding-a-d2d-object-to-an-mfc-project.md
  docs/mfc/walkthrough-adding-animation-to-an-mfc-project.md
  docs/mfc/walkthrough-creating-a-ribbon-application-by-using-mfc.md
  docs/mfc/walkthrough-putting-controls-on-toolbars.md
  docs/mfc/walkthrough-updating-the-mfc-scribble-application-part-1.md
  docs/mfc/walkthrough-updating-the-mfc-scribble-application-part-2.md
  docs/mfc/walkthrough-using-the-new-mfc-shell-controls.md
Labels: Change sent to author

#974 Correct size based alignment for global data
  docs/build/arm64-windows-abi-conventions.md
Labels: Change sent to author, do-not-merge

#977 Fix git push error for protected CLA branch
  docs/assembler/masm/masm-for-x64-ml64-exe.md
  docs/build/building-on-the-command-line.md
  docs/build/cmake-projects-in-visual-studio.md
  docs/build/cmakesettings-reference.md
  docs/build/customize-cmake-settings.md
  docs/build/how-to-create-a-cpp-project-from-existing-code.md
  docs/build/media/cmake-settings-editor.png
  docs/build/media/cmake-settings-solution-explorer.png
  docs/build/media/create-new-dll-project-2019.png
  docs/build/media/mathclient-project-name-2019.png
  docs/build/media/vs2019-cmake-configure-options.png
  docs/build/media/vs2019-cmake-manage-configurations.png
  docs/build/walkthrough-compile-a-c-program-on-the-command-line.md
  docs/build/walkthrough-compiling-a-cpp-cli-program-on-the-command-line.md
  docs/build/walkthrough-compiling-a-cpp-cx-program-on-the-command-line.md
  docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md
  docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md
  docs/build/walkthrough-creating-and-using-a-static-library-cpp.md
  docs/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project.md
  docs/cppcx/static-libraries-c-cx.md
  docs/dotnet/walkthrough-compiling-a-cpp-program-that-targets-the-clr-in-visual-studio.md
  docs/ide/walkthrough-working-with-projects-and-solutions-cpp.md
  docs/linux/cmake-linux-project.md
  docs/mfc/reference/cdbexception-class.md
  docs/overview/media/vs2017-team-explorer.png
  docs/overview/media/vs2019-team-explorer.png
  docs/overview/overview-of-cpp-development.md
  docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md
  docs/parallel/amp/walkthrough-matrix-multiplication.md
  docs/standard-library/forward-list-class.md
  docs/windows/deploying-visual-cpp-application-by-using-the-vcpp-redistributable-package.md
  docs/windows/media/vs2019-extension-dialog-installer-project.png
  docs/windows/media/vs2019-mfc-app-new-project.png
  docs/windows/walkthrough-creating-a-standard-cpp-program-cpp.md
  docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md
  docs/windows/walkthrough-deploying-a-visual-cpp-application-by-using-a-setup-project.md
  docs/windows/walkthrough-deploying-a-visual-cpp-application-to-an-application-local-folder.md
Labels: Change sent to author
