Repository MicrosoftDocs/cpp-docs, pull requests merged in 2019-01, with the labels that each got.

#653 Update generic-text-mappings-in-tchar-h.md
  docs/text/generic-text-mappings-in-tchar-h.md
Labels: Change sent to author, do-not-merge

#665 Update how-to-convert-between-various-string-types.md
  docs/text/how-to-convert-between-various-string-types.md
Labels: Change sent to author, do-not-merge

#664 Update how-to-convert-between-various-string-types.md
  docs/text/how-to-convert-between-various-string-types.md
Labels: Change sent to author, do-not-merge

#666 Update cpp-language-reference.md
  docs/cpp/cpp-language-reference.md
Labels: Change sent to author, do-not-merge

#671 Update _setmode() to clarify Unicode mode use case
  docs/c-runtime-library/reference/setmode.md
Labels: Change sent to author, do-not-merge

#675 Fix git push error for protected CLA branch
  docs/assembler/masm/align-masm.md
  docs/c-runtime-library/reference/fopen-wfopen.md
Labels: Change sent to author

#699 __[read/write/inc/add]gsqword intrinsics are not kernel specific.
  docs/intrinsics/addgsbyte-addgsword-addgsdword-addgsqword.md
  docs/intrinsics/incgsbyte-incgsword-incgsdword-incgsqword.md
  docs/intrinsics/readgsbyte-readgsdword-readgsqword-readgsword.md
  docs/intrinsics/writegsbyte-writegsdword-writegsqword-writegsword.md
Labels: Change sent to author, do-not-merge

#677 fix style
  docs/c-runtime-library/bufsiz.md
  docs/c-runtime-library/clocks-per-sec-clk-tck.md
  docs/c-runtime-library/eof-weof.md
  docs/c-runtime-library/errno-constants.md
  docs/c-runtime-library/file-attribute-constants.md
  docs/c-runtime-library/file-constants.md
  docs/c-runtime-library/file-permission-constants.md
  docs/c-runtime-library/fopen-max-sys-open.md
  docs/c-runtime-library/fseek-lseek-constants.md
  docs/c-runtime-library/heap-constants.md
  docs/c-runtime-library/heap-maxreq.md
  docs/c-runtime-library/huge-val-huge.md
  docs/c-runtime-library/locale-categories.md
  docs/c-runtime-library/math-error-constants.md
  docs/c-runtime-library/max-env.md
  docs/c-runtime-library/mb-cur-max.md
  docs/c-runtime-library/rand-max.md
  docs/c-runtime-library/setvbuf-constants.md
  docs/c-runtime-library/sharing-constants.md
  docs/c-runtime-library/stat-structure-st-mode-field-constants.md
  docs/c-runtime-library/translation-mode-constants.md
  docs/c-runtime-library/wait-child-wait-grandchild.md
Labels: Change sent to author, do-not-merge

#680 Update cpp-type-system-modern-cpp.md
  docs/cpp/cpp-type-system-modern-cpp.md
Labels: Change sent to author, do-not-merge

#681 Update value-types-modern-cpp.md
  docs/cpp/value-types-modern-cpp.md
Labels: Change sent to author, do-not-merge

#682 Update type-conversions-and-type-safety-modern-cpp.md
  docs/cpp/type-conversions-and-type-safety-modern-cpp.md
Labels: Change sent to author, do-not-merge

#683 Update object-lifetime-and-resource-management-modern-cpp.md
  docs/cpp/object-lifetime-and-resource-management-modern-cpp.md
Labels: Change sent to author, do-not-merge

#684 Update objects-own-resources-raii.md
  docs/cpp/objects-own-resources-raii.md
Labels: Change sent to author, do-not-merge

#685 Update smart-pointers-modern-cpp.md
  docs/cpp/smart-pointers-modern-cpp.md
Labels: Change sent to author, do-not-merge

#686 Update how-to-create-and-use-unique-ptr-instances.md
  docs/cpp/how-to-create-and-use-unique-ptr-instances.md
Labels: Change sent to author, do-not-merge

#687 Update how-to-create-and-use-shared-ptr-instances.md
  docs/cpp/how-to-create-and-use-shared-ptr-instances.md
Labels: Change sent to author, do-not-merge

#688 Update how-to-create-and-use-weak-ptr-instances.md
  docs/cpp/how-to-create-and-use-weak-ptr-instances.md
Labels: Change sent to author, do-not-merge

#689 Update how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md
  docs/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md
Labels: Change sent to author, do-not-merge

#690 Update pimpl-for-compile-time-encapsulation-modern-cpp.md
  docs/cpp/pimpl-for-compile-time-encapsulation-modern-cpp.md
Labels: Change sent to author, do-not-merge

#691 Update containers-modern-cpp.md
  docs/cpp/containers-modern-cpp.md
Labels: Change sent to author, do-not-merge

#692 Update algorithms-modern-cpp.md
  docs/cpp/algorithms-modern-cpp.md
Labels: Change sent to author, do-not-merge

#693 Update string-and-i-o-formatting-modern-cpp.md
  docs/cpp/string-and-i-o-formatting-modern-cpp.md
Labels: Change sent to author, do-not-merge

#694 Update errors-and-exception-handling-modern-cpp.md
  docs/cpp/errors-and-exception-handling-modern-cpp.md
Labels: Change sent to author, do-not-merge

#695 Update how-to-design-for-exception-safety.md
  docs/cpp/how-to-design-for-exception-safety.md
Labels: Change sent to author, do-not-merge

#696 Update how-to-interface-between-exceptional-and-non-exceptional-code.md
  docs/cpp/how-to-interface-between-exceptional-and-non-exceptional-code.md
Labels: Change sent to author, do-not-merge

#697 Update portability-at-abi-boundaries-modern-cpp.md
  docs/cpp/portability-at-abi-boundaries-modern-cpp.md
Labels: Change sent to author, do-not-merge

#702 umul128: Only available on x64
  docs/intrinsics/umul128.md
Labels: Change sent to author, do-not-merge

#704 Add ARM and ARM64 to supported arch for __nop
  docs/intrinsics/nop.md
Labels: Change sent to author, do-not-merge

#705 Fix git push error for protected CLA branch
  docs/docfx.json
Labels: Change sent to author

#712 Fix git push error for protected CLA branch
  docs/build/exporting-from-a-dll-using-def-files.md
  docs/c-language/c-floating-point-constants.md
Labels: Change sent to author

#726 Remove typo (double s in "directives").
  docs/build/reference/fp-specify-floating-point-behavior.md
Labels: Change sent to author, do-not-merge

#723 Update detect-mismatch.md
  docs/preprocessor/detect-mismatch.md
Labels: Change sent to author, do-not-merge

#722 Wrong Error Specified in unlink/remove
  docs/c-runtime-library/reference/remove-wremove.md
  docs/c-runtime-library/reference/unlink-wunlink.md
Labels: Change sent to author, do-not-merge

#727 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/ide/TOC.md
  docs/ide/how-to-create-a-cpp-project-from-existing-code.md
  docs/ide/media/config.png
  docs/ide/media/location.png
  docs/ide/media/settings.png
  docs/ide/specify-debug-configuration-settings.md
  docs/ide/specify-project-location-and-source-files.md
  docs/ide/specify-project-settings-create-new-project-from-existing-code-files-wizard.md
  docs/ide/specify-release-configuration.md
  docs/parallel/openmp/1-1-scope.md
  docs/parallel/openmp/1-2-definition-of-terms.md
  docs/parallel/openmp/1-3-execution-model.md
  docs/parallel/openmp/1-4-compliance.md
  docs/parallel/openmp/1-5-normative-references.md
  docs/parallel/openmp/1-6-organization.md
  docs/parallel/openmp/1-introduction.md
  docs/parallel/openmp/4-1-omp-schedule.md
  docs/parallel/openmp/4-2-omp-num-threads.md
  docs/parallel/openmp/4-3-omp-dynamic.md
  docs/parallel/openmp/4-4-omp-nested.md
  docs/parallel/openmp/4-environment-variables.md
  docs/parallel/openmp/TOC.md
  docs/parallel/openmp/c-1-notation.md
  docs/parallel/openmp/c-2-rules.md
  docs/parallel/openmp/c-openmp-c-and-cpp-grammar.md
  docs/parallel/openmp/contents.md
Labels: Change sent to author

#731 Update fp-specify-floating-point-behavior.md
  docs/build/reference/fp-specify-floating-point-behavior.md
Labels: Change sent to author, do-not-merge

#728 Update struct-cpp.md
  docs/cpp/struct-cpp.md
Labels: Change sent to author, do-not-merge

#730 Update main-program-startup.md
  docs/cpp/main-program-startup.md
Labels: Change sent to author, do-not-merge

#737 Update visual-cpp-what-s-new-2003-through-2015.md
  docs/porting/visual-cpp-what-s-new-2003-through-2015.md
Labels: do-not-merge

#738 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/dotnet/TOC.md
  docs/dotnet/auto-handle-auto-handle.md
  docs/dotnet/auto-handle-class.md
  docs/dotnet/auto-handle-get.md
  docs/dotnet/auto-handle-members.md
  docs/dotnet/auto-handle-operator-arrow.md
  docs/dotnet/auto-handle-operator-assign.md
  docs/dotnet/auto-handle-operator-auto-handle.md
  docs/dotnet/auto-handle-operator-bool.md
  docs/dotnet/auto-handle-operator-logical-not.md
  docs/dotnet/auto-handle-release.md
  docs/dotnet/auto-handle-reset.md
  docs/dotnet/auto-handle-swap.md
  docs/dotnet/auto-handle-tilde-auto-handle.md
  docs/dotnet/com-ptr-class.md
  docs/dotnet/lock-acquire.md
  docs/dotnet/lock-class.md
  docs/dotnet/lock-is-locked.md
  docs/dotnet/lock-lock.md
  docs/dotnet/lock-members.md
  docs/dotnet/lock-operator-bool.md
  docs/dotnet/lock-operator-equality.md
  docs/dotnet/lock-operator-inequality.md
  docs/dotnet/lock-release.md
  docs/dotnet/lock-tilde-lock.md
  docs/dotnet/lock-try-acquire.md
  docs/dotnet/marshal-context-class.md
  docs/dotnet/marshal-context-marshal-as.md
  docs/dotnet/marshal-context-marshal-context.md
  docs/dotnet/marshal-context-tilde-marshal-context.md
  docs/dotnet/ptr-attach.md
  docs/dotnet/ptr-createinstance.md
  docs/dotnet/ptr-detach.md
  docs/dotnet/ptr-getinterface.md
  docs/dotnet/ptr-members.md
  docs/dotnet/ptr-operator-arrow.md
  docs/dotnet/ptr-operator-assign.md
  docs/dotnet/ptr-operator-bool.md
  docs/dotnet/ptr-operator-logical-not.md
  docs/dotnet/ptr-ptr.md
  docs/dotnet/ptr-queryinterface.md
  docs/dotnet/ptr-release.md
  docs/dotnet/ptr-tilde-ptr.md
Labels: Change sent to author, do-not-merge
