Repository MicrosoftDocs/cpp-docs, pull requests merged in 2019-09, with the labels that each got.

#1539 Update bitscanforward-bitscanforward64.md
  docs/intrinsics/bitscanforward-bitscanforward64.md
Labels: Change sent to author, do-not-merge

#1536 Remove the dot
  docs/ide/walkthrough-testing-a-project-cpp.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1560 Update fflush sample
  docs/c-runtime-library/reference/fflush.md
Labels: Change sent to author, do-not-merge

#1566 Fix git push error for protected CLA branch
  docs/intrinsics/intrinsics-available-on-all-architectures.md
Labels: do-not-merge

#1565 Updated parameters name.
  docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1567 Add missing space
  docs/atl/reference/debugging-and-error-reporting-macros.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1568 Fix git push error for protected CLA branch
  docs/cpp/codesnippet/CPP/how-to-create-and-use-weak-ptr-instances_1.cpp
  docs/cpp/constructors-cpp.md
  docs/cpp/unions.md
Labels: do-not-merge

#1569 Fixed typo (messsage)
  docs/standard-library/filesystem-error-class.md
Labels: Change sent to author, do-not-merge

#1570 Fixed typo (errror)
  docs/error-messages/compiler-warnings/compiler-warning-c4335.md
Labels: Change sent to author, do-not-merge

#1573 Fix git push error for protected CLA branch
  docs/cpp/how-to-create-and-use-weak-ptr-instances.md
  docs/standard-library/cstdlib.md
  docs/windows/overview-of-windows-programming-in-cpp.md
Labels: assessing_(C&L), do-not-merge

#1581 Update how to enable ASAN
  docs/linux/linux-asan-configuration.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1583 Fix git push error for protected CLA branch
  docs/build/reference/d-preprocessor-definitions.md
  docs/error-messages/compiler-warnings/c5105.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4577.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4510.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4400-through-c4599.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md
  docs/error-messages/toc.yml
  docs/error-messages/tool-errors/resource-compiler-error-rw2002.md
Labels: do-not-merge

#1586 Fix git push error for protected CLA branch
  docs/build/projects-and-build-systems-cpp.md
  docs/c-runtime-library/reference/getcwd-wgetcwd.md
  docs/cloud/cloud-and-web-programming-in-visual-cpp.md
  docs/cpp/c-cpp-language-and-standard-libraries.md
  docs/cppcx/universal-windows-apps-cpp.md
  docs/cppcx/wrl/windows-runtime-cpp-template-library-wrl.md
  docs/extensions/component-extensions-for-runtime-platforms.md
  docs/ide/writing-and-refactoring-code-cpp.md
  docs/mfc/mfc-and-atl.md
  docs/parallel/parallel-programming-in-visual-cpp.md
  docs/porting/visual-cpp-porting-and-upgrading-guide.md
  docs/windows/deploying-native-desktop-applications-visual-cpp.md
  docs/windows/desktop-applications-visual-cpp.md
Labels: do-not-merge

#1588 Fix git push error for protected CLA branch
  docs/overview/cpp-conformance-improvements.md
  docs/preprocessor/compiler-warnings-that-are-off-by-default.md
Labels: do-not-merge
