Repository MicrosoftDocs/cpp-docs, pull requests merged in 2019-06, with the labels that each got.

#1052 Fix title
  docs/build/reference/vmb-vmg-representation-method.md
Labels: Change sent to author, do-not-merge

#1053 Fix git push error for protected CLA branch
  docs/build/reference/fp-name-dot-pch-file.md
Labels: Change sent to author

#1056 Single : missing to make scope resolution operator
  docs/cpp/how-to-create-and-use-shared-ptr-instances.md
Labels: Change sent to author, do-not-merge

#1059 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/ide/adding-functionality-with-code-wizards-cpp.md
  docs/ide/live-share-cpp.md
  docs/ide/media/change-tracking-cpp.png
  docs/ide/media/clang-format-cpp.png
  docs/ide/media/class-view.png
  docs/ide/media/code-outline-colorization.png
  docs/ide/media/cpp-statement-completion.png
  docs/ide/media/edit-advanced-cpp.png
  docs/ide/media/find-all-references-filters-cpp.png
  docs/ide/media/find-all-references-results-cpp.png
  docs/ide/media/find-cpp.png
  docs/ide/media/find-in-files-cpp.png
  docs/ide/media/go-to-cpp.png
  docs/ide/media/go-to-def.png
  docs/ide/media/go-to-document.png
  docs/ide/media/go-to-menu-cpp.png
  docs/ide/media/inactive-code-cpp.png
  docs/ide/media/intellicode-cpp.png
  docs/ide/media/live-share-button-cpp.png
  docs/ide/media/live-share-debug-cpp.png
  docs/ide/media/live-share-edit-cpp.png
  docs/ide/media/live-share-end-session-cpp.png
  docs/ide/media/navbar-cpp.png
  docs/ide/media/parameter-info.png
  docs/ide/media/predictive-intellisense-cpp.png
  docs/ide/media/quick-fix-for-header-cpp.png
  docs/ide/media/quick-fix.png
  docs/ide/media/quick-info-vs2019.png
  docs/ide/media/quick-info.png
  docs/ide/media/quickinfo-on-error.png
  docs/ide/media/template-intellisense-cpp-1.png
  docs/ide/media/template-intellisense-cpp-2.png
  docs/ide/media/template-intellisense-cpp-3.png
  docs/ide/media/template-intellisense-cpp-4.png
  docs/ide/media/tools-options.png
  docs/ide/media/vs2015-cpp-code-map.png
  docs/ide/media/vs2015_cpp_add_class.png
  docs/ide/media/vs2015_cpp_class_wizard.png
  docs/ide/media/vs2015_cpp_code_map.png
  docs/ide/media/vs2015_cpp_open_document.png
  docs/ide/media/vs2015_cpp_statement_completion.png
  docs/ide/media/vs2017-add-class.png
  docs/ide/media/vs2017-class-wizard.png
  docs/ide/media/vs2017-find-in-files-results.png
  docs/ide/media/vs2017-go-to-results.png
  docs/ide/media/zoom-control.png
  docs/ide/navigate-code-cpp.md
  docs/ide/navigating-the-class-structure-visual-cpp.md
  docs/ide/read-and-understand-code-cpp.md
  docs/ide/writing-and-refactoring-code-cpp.md
  docs/mfc/reference/adding-an-mfc-message-handler.md
  docs/mfc/reference/adding-atl-support-to-your-mfc-project.md
  docs/mfc/reference/declaring-a-variable-based-on-your-new-control-class.md
  docs/mfc/reference/defining-a-message-handler-for-a-reflected-message.md
  docs/mfc/reference/details-of-atl-support-added-by-the-atl-wizard.md
  docs/mfc/reference/editing-a-message-handler.md
  docs/mfc/reference/mapping-messages-to-functions.md
  docs/mfc/reference/message-types-associated-with-user-interface-objects.md
  docs/toc.yml
Labels: do-not-merge

#1070 Fix git push error for protected CLA branch
  docs/build/building-on-the-command-line.md
  docs/build/reference/cl-environment-variables.md
  docs/c-runtime-library/reference/get-osfhandle.md
  docs/c-runtime-library/reference/open-osfhandle.md
  docs/linux/cmake-linux-project.md
  docs/linux/configure-a-linux-project.md
  docs/linux/connect-to-your-remote-linux-computer.md
  docs/linux/create-a-new-linux-project.md
  docs/linux/deploy-run-and-debug-your-linux-project.md
  docs/linux/download-install-and-setup-the-linux-development-workload.md
  docs/linux/index.md
  docs/linux/linux-asan-configuration.md
  docs/linux/media/asan-error.png
  docs/linux/media/cmake-settings-asan-options.png
  docs/linux/media/connection-manager-vs2019.png
  docs/linux/media/linux-console-new-project.png
  docs/linux/media/linux-debug-configuration.png
  docs/linux/media/linux-general-prop-page-vs2019.png
  docs/linux/media/msbuild-asan-prop-page.png
  docs/linux/media/msbuild-asan-runtime-flags.png
  docs/linux/media/newproject-vs2019.png
  docs/linux/media/remote-build-machine-vs2019.png
  docs/linux/media/remote-logging-vs2019.png
  docs/linux/media/settings_debugger.png
  docs/linux/media/vs2017-debugger-settings.png
  docs/linux/media/vs2019-debugger-settings.png
  docs/linux/media/wsl-cmake-binaries-installation.png
  docs/linux/media/wsl-remote-vs2019.png
  docs/linux/prop-pages/build-events-linux.md
  docs/linux/prop-pages/c-cpp-linux.md
  docs/linux/prop-pages/copy-sources-project.md
  docs/linux/prop-pages/custom-build-step-linux.md
  docs/linux/prop-pages/debugging-linux.md
  docs/linux/prop-pages/directories-linux.md
  docs/linux/prop-pages/general-linux.md
  docs/linux/prop-pages/linker-linux.md
  docs/linux/prop-pages/makefile-linux.md
  docs/linux/prop-pages/remote-ar-linux.md
  docs/linux/toc.yml
Labels: Change sent to author, do-not-merge

#1085 Fix git push error for protected CLA branch
  docs/build/cmake-predefined-configuration-reference.md
  docs/build/cmake-projects-in-visual-studio.md
  docs/build/cmakesettings-reference.md
  docs/build/customize-cmake-settings.md
  docs/build/media/cmake-install-2019.png
  docs/build/open-folder-projects-cpp.md
  docs/linux/cmake-linux-project.md
  docs/linux/configure-a-linux-project.md
  docs/linux/connect-to-your-remote-linux-computer.md
  docs/linux/create-a-new-linux-project.md
  docs/linux/deploy-run-and-debug-your-linux-project.md
  docs/linux/download-install-and-setup-the-linux-development-workload.md
  docs/linux/index.md
  docs/linux/media/cmake-remote-debug-machine.png
  docs/linux/media/linux-deployable-content.png
  docs/linux/media/linux-remote-debug-machine.png
  docs/linux/toc.yml
Labels: Change sent to author, do-not-merge

#1089 Fix git push error for protected CLA branch
  docs/atl/codesnippet/CPP/isupporterrorinfoimpl-class_2.cpp
  docs/atl/reference/isupporterrorinfoimpl-class.md
  docs/build/reference/verbose-print-progress-messages.md
  docs/cpp/references-to-pointers.md
  docs/mfc/reference/clistctrl-class.md
Labels: Change sent to author, do-not-merge

#1087 Update link-pass-options-to-linker.md
  docs/build/reference/link-pass-options-to-linker.md
Labels: Change sent to author, do-not-merge

#1097 Remove duplicate links
  docs/mfc/optimizing-control-drawing.md
Labels: Change sent to author, do-not-merge

#1091 Missing {}
  docs/standard-library/algorithm-functions.md
Labels: Change sent to author, do-not-merge

#1092 Example of all_of
  docs/standard-library/algorithm-functions.md
Labels: Change sent to author, do-not-merge

#1093 ?! what are you talking about
  docs/standard-library/algorithm-functions.md
Labels: Change sent to author, do-not-merge

#1094 Example any_of
  docs/standard-library/algorithm-functions.md
Labels: Change sent to author, do-not-merge

#1106 Fix git push error for protected CLA branch
  docs/overview/2017/cpp-conformance-improvements-2017.md
  docs/overview/2019/cpp-conformance-improvements-2019.md
  docs/overview/cpp-conformance-improvements.md
Labels: Change sent to author, cpp-language/tech, do-not-merge

#1100 :-)
  docs/standard-library/algorithm-functions.md
Labels: Change sent to author, do-not-merge

#1113 Fix git push error for protected CLA branch
  docs/linux/connect-to-your-remote-linux-computer.md
Labels: Change sent to author

#1109 Add encoding of __debugbreak() for ARM64
  docs/intrinsics/debugbreak.md
Labels: Change sent to author, do-not-merge

#1104 example to copy_n
  docs/standard-library/algorithm-functions.md
Labels: Change sent to author, do-not-merge

#1160 Remove duplicate links
  docs/c-runtime-library/reference/malloc-dbg.md
Labels: Change sent to author, do-not-merge

#1159 Remove duplicate links
  docs/c-runtime-library/reference/filelength-filelengthi64.md
Labels: Change sent to author, do-not-merge

#1294 Update os-ot-favor-small-code-favor-fast-code.md
  docs/build/reference/os-ot-favor-small-code-favor-fast-code.md
Labels: Change sent to author, do-not-merge

#1296 Fix git push error for protected CLA branch
  docs/build/reference/gd-gr-gv-gz-calling-convention.md
  docs/build/reference/ltcg-link-time-code-generation.md
  docs/build/release-builds.md
  docs/build/understanding-custom-build-steps-and-build-events.md
  docs/c-language/c-integer-constants.md
  docs/c-language/c-primary-expressions.md
  docs/c-language/c-relational-and-equality-operators.md
  docs/c-language/c-string-literals.md
  docs/cpp/try-except-statement.md
  docs/cpp/try-finally-statement.md
  docs/extensions/new-new-slot-in-vtable-cpp-component-extensions.md
  docs/ide/walkthrough-building-a-project-cpp.md
  docs/ide/walkthrough-debugging-a-project-cpp.md
  docs/ide/walkthrough-deploying-your-program-cpp.md
  docs/ide/walkthrough-testing-a-project-cpp.md
  docs/ide/walkthrough-working-with-projects-and-solutions-cpp.md
  docs/overview/libraries-cpp.md
  docs/overview/visual-cpp-language-conformance.md
  docs/overview/visual-cpp-tools-and-features-in-visual-studio-editions.md
  docs/porting/upgrading-projects-from-earlier-versions-of-visual-cpp.md
  docs/preprocessor/compiler-warnings-that-are-off-by-default.md
  docs/standard-library/iterators.md
  docs/standard-library/promise-class.md
  docs/standard-library/regex-constants-class.md
  docs/standard-library/regex-traits-class.md
  docs/standard-library/unique-lock-class.md
  docs/windows/adding-editing-or-deleting-controls.md
  docs/windows/controls-in-dialog-boxes.md
  docs/windows/menu-command-properties.md
  docs/windows/walkthrough-creating-a-standard-cpp-program-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge
