Repository MicrosoftDocs/cpp-docs, pull requests merged in 2019-12, with the labels that each got.

#1751 Update initializing-classes-and-structs-without-constructors-cpp.md
  docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#1758 Add link to DevCom ticket
  docs/linux/connect-to-your-remote-linux-computer.md
Labels: Change sent to author, cpp-linux/tech, do-not-merge, visual-cpp/prod

#1759 Update cpp-library-conventions.md
  docs/standard-library/cpp-library-conventions.md
Labels: Change sent to author, cpp-standard-libraries/tech, do-not-merge, visual-cpp/prod

#1775 Fix git push error for protected CLA branch
  docs/assembler/masm/dot-pushframe.md
Labels: do-not-merge

#1777 Remove duplicate configuration properties
  docs/build/cmakesettings-reference.md
Labels: do-not-merge, review-team-triage

#1778 Add remark about _aligned_malloc and free
  docs/c-runtime-library/reference/aligned-malloc.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1780 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/cpp/abort-function.md
  docs/cpp/additional-startup-considerations.md
  docs/cpp/argument-definitions.md
  docs/cpp/auto-cpp.md
  docs/cpp/auto-keyword.md
  docs/cpp/basic-concepts-cpp.md
  docs/cpp/character-sets.md
  docs/cpp/cpp-language-reference.md
  docs/cpp/customizing-cpp-command-line-processing.md
  docs/cpp/declarations-and-definitions-cpp.md
  docs/cpp/exit-function.md
  docs/cpp/functions-cpp.md
  docs/cpp/lexical-conventions.md
  docs/cpp/main-function-command-line-args.md
  docs/cpp/main-function-restrictions.md
  docs/cpp/main-program-startup.md
  docs/cpp/numeric-boolean-and-pointer-literals-cpp.md
  docs/cpp/overview-of-declarators.md
  docs/cpp/overview-of-file-translation.md
  docs/cpp/parsing-cpp-command-line-arguments.md
  docs/cpp/point-of-declaration-in-cpp.md
  docs/cpp/program-termination.md
  docs/cpp/resolving-ambiguous-declarations-cpp.md
  docs/cpp/return-statement-in-program-termination-cpp.md
  docs/cpp/specifiers.md
  docs/cpp/startup-and-termination-cpp.md
  docs/cpp/tokens-cpp.md
  docs/cpp/user-defined-literals-cpp.md
  docs/cpp/using-atexit.md
  docs/cpp/using-exit-or-return.md
  docs/cpp/using-wmain-instead-of-main.md
  docs/cpp/wildcard-expansion.md
  docs/parallel/concrt/general-best-practices-in-the-concurrency-runtime.md
  docs/parallel/concrt/parallel-containers-and-objects.md
  docs/parallel/concrt/reference/concurrent-queue-class.md
  docs/parallel/concrt/reference/concurrent-unordered-map-class.md
  docs/parallel/concrt/reference/concurrent-unordered-multimap-class.md
  docs/parallel/concrt/reference/concurrent-unordered-multiset-class.md
  docs/parallel/concrt/reference/concurrent-unordered-set-class.md
  docs/parallel/concrt/reference/concurrent-vector-class.md
  docs/toc.yml
Labels: do-not-merge

#1786 Fix broken links to Windows docs
  docs/atl/iunknown.md
  docs/atl/queryinterface.md
  docs/atl/reference/ccomptrbase-class.md
  docs/mfc/tn038-mfc-ole-iunknown-implementation.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1788 Add language identifiers
  docs/build/why-floating-point-numbers-may-lose-precision.md
  docs/c-language/goto-and-labeled-statements-c.md
  docs/c-language/one-dimensional-arrays.md
  docs/c-language/parsing-c-command-line-arguments.md
  docs/c-language/summary-of-lifetime-and-visibility.md
  docs/c-runtime-library/cgets-cgetws.md
  docs/c-runtime-library/exec-wexec-functions.md
  docs/c-runtime-library/filename-search-functions.md
  docs/c-runtime-library/gets-getws.md
  docs/c-runtime-library/heapset.md
  docs/c-runtime-library/pgmptr-wpgmptr.md
  docs/c-runtime-library/spawn-wspawn-functions.md
  docs/c-runtime-library/to-functions.md
  docs/c-runtime-library/truncate.md
  docs/error-messages/compiler-errors-1/compiler-error-c2032.md
  docs/error-messages/compiler-errors-1/compiler-error-c2036.md
  docs/error-messages/compiler-errors-1/compiler-error-c2053.md
  docs/error-messages/compiler-errors-1/compiler-error-c2054.md
  docs/error-messages/compiler-errors-1/compiler-error-c2055.md
  docs/error-messages/compiler-errors-1/compiler-error-c2057.md
  docs/error-messages/compiler-errors-1/compiler-error-c2063.md
  docs/error-messages/compiler-errors-1/compiler-error-c2075.md
  docs/error-messages/compiler-errors-1/compiler-error-c2081.md
  docs/error-messages/compiler-errors-1/compiler-error-c2085.md
  docs/error-messages/compiler-errors-1/compiler-error-c2088.md
  docs/error-messages/compiler-errors-1/compiler-error-c2093.md
  docs/error-messages/compiler-errors-1/compiler-error-c2099.md
  docs/error-messages/compiler-errors-1/compiler-error-c2142.md
  docs/error-messages/compiler-errors-1/compiler-error-c2164.md
  docs/error-messages/compiler-errors-1/compiler-error-c2180.md
  docs/error-messages/compiler-errors-1/compiler-error-c2190.md
  docs/error-messages/compiler-errors-1/compiler-error-c2191.md
  docs/error-messages/compiler-errors-1/compiler-error-c2192.md
  docs/error-messages/compiler-errors-1/compiler-error-c2197.md
  docs/error-messages/compiler-errors-1/compiler-error-c2198.md
  docs/error-messages/compiler-errors-1/compiler-error-c2231.md
  docs/error-messages/compiler-errors-1/compiler-error-c2232.md
  docs/error-messages/compiler-errors-1/compiler-error-c2268.md
  docs/error-messages/compiler-errors-1/compiler-error-c2379.md
  docs/error-messages/compiler-errors-1/compiler-error-c2449.md
  docs/error-messages/compiler-errors-1/compiler-error-c2467.md
  docs/error-messages/compiler-errors-2/compiler-error-c3001.md
  docs/error-messages/compiler-errors-2/compiler-error-c3002.md
  docs/error-messages/compiler-errors-2/compiler-error-c3003.md
  docs/error-messages/compiler-errors-2/compiler-error-c3004.md
  docs/error-messages/compiler-errors-2/compiler-error-c3005.md
  docs/error-messages/compiler-errors-2/compiler-error-c3006.md
  docs/error-messages/compiler-errors-2/compiler-error-c3007.md
  docs/error-messages/compiler-errors-2/compiler-error-c3008.md
  docs/error-messages/compiler-errors-2/compiler-error-c3009.md
  docs/error-messages/compiler-errors-2/compiler-error-c3010.md
Labels: assessing_(C&L), do-not-merge

#1793 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/mfc/receiving-notification-from-common-controls.md
  docs/mfc/reference/handlers-for-wm-messages.md
  docs/mfc/tn061-on-notify-and-wm-notify-messages.md
  docs/mfc/using-a-dialog-bar-with-a-rebar-control.md
  docs/preprocessor/conventions.md
  docs/preprocessor/definitions-for-the-grammar-summary.md
  docs/preprocessor/grammar-summary-c-cpp.md
  docs/preprocessor/preprocessor-grammar.md
  docs/toc.yml
Labels: assessing_(C&L), do-not-merge

#1795 Clarify removal of vcpkg directory uninstalls all libraries
  docs/build/vcpkg.md
Labels: Change sent to author, assessing_(C&L), cpp-ide/tech, do-not-merge, visual-cpp/prod

#1804 Fix git push error for protected CLA branch
  docs/build/reference/dependentloadflag.md
Labels: do-not-merge
