Repository MicrosoftDocs/cpp-docs, pull requests merged in 2019-10, with the labels that each got.

#1595 Fix git push error for protected CLA branch
  docs/build/reference/linker-options.md
  docs/build/reference/linkreprotarget.md
  docs/preprocessor/compiler-warnings-that-are-off-by-default.md
Labels: do-not-merge

#1598 Remove what's new in 2019?
  docs/build/cmake-projects-in-visual-studio.md
Labels: Change sent to author, do-not-merge

#1599 Update "Installation" and "IDE Integration"
  docs/build/cmake-projects-in-visual-studio.md
Labels: Change sent to author, do-not-merge

#1592 Add more prominent overview links to CX Vector & Map
  docs/cppcx/platform-collections-map-class.md
  docs/cppcx/platform-collections-vector-class.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1602 Document /arch:AVX512 command-line option
  docs/build/reference/arch-x64.md
  docs/build/reference/arch-x86.md
  docs/preprocessor/predefined-macros.md
Labels: Change sent to author, do-not-merge

#1601 Final changes
  docs/build/cmake-projects-in-visual-studio.md
Labels: Change sent to author, do-not-merge

#1600 Change "import existing cache" to "open existing cache"
  docs/build/cmake-projects-in-visual-studio.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1606 Update required dependencies + small edits
  docs/linux/download-install-and-setup-the-linux-development-workload.md
Labels: Change sent to author, do-not-merge

#1607 Include clang or gcc
  docs/linux/connect-to-your-remote-linux-computer.md
Labels: Change sent to author, do-not-merge

#1608 update intellisense for wsl
  docs/linux/configure-a-linux-project.md
Labels: Change sent to author, do-not-merge

#1612 Fix the encoding of the MSFT_OP_* unwind codes in ARM64.
  docs/build/arm64-exception-handling.md
Labels: Change sent to author, do-not-merge

#1613 Rename reference for distinction
  docs/dotnet/differences-in-exception-handling-behavior-under-clr.md
Labels: Change sent to author, do-not-merge

#1615 Update linker-tools-error-lnk2019.md
  docs/error-messages/tool-errors/linker-tools-error-lnk2019.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1625 Update openmp-library-reference.md
  docs/parallel/openmp/reference/openmp-library-reference.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1629 Update debug commands
  docs/build/configure-cmake-debugging-sessions.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1632 Fix git push error for protected CLA branch
  docs/build/exception-handling-x64.md
  docs/build/how-to-add-a-custom-build-step-to-msbuild-projects.md
  docs/build/reference/analyze-code-analysis.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4127.md
  docs/linux/prop-pages/copy-sources-project.md
  docs/mfc/codesnippet/CPP/cbrush-class_1.cpp
  docs/windows/dialog-editor.md
  docs/windows/how-to-create-a-resource-script-file.md
  docs/windows/menu-editor.md
  docs/windows/resource-editors.md
Labels: assessing_(C&L), do-not-merge

#1635 Update Binary Compatibility page
  docs/porting/binary-compat-2015-2017.md
Labels: Change sent to author, do-not-merge

#1638 Fix git push error for protected CLA branch
  docs/cpp/constructors-cpp.md
  docs/cppcx/platform-arrayreference-class.md
  docs/cppcx/platform-string-class.md
  docs/preprocessor/variadic-macros.md
Labels: do-not-merge

#1643 Fix header levels
  docs/windows/desktop-applications-visual-cpp.md
Labels: Change sent to author, do-not-merge

#1644 match voice-tone.md with dotnet/docs repo
  styleguide/voice-tone.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1649 Fix git push error for protected CLA branch
  docs/build/building-on-the-command-line.md
  docs/c-runtime-library/interpretation-of-multibyte-character-sequences.md
  docs/c-runtime-library/reference/bsearch-s.md
  docs/c-runtime-library/reference/bsearch.md
  docs/c-runtime-library/reference/c16rtomb-c32rtomb1.md
  docs/c-runtime-library/reference/mbrtoc16-mbrtoc323.md
  docs/c-runtime-library/scanf-width-specification.md
  docs/error-messages/tool-errors/linker-tools-error-lnk2019.md
Labels: do-not-merge

#1652 Short description is wrong/misleading
  docs/standard-library/is-move-constructible-class.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1546 Use <iostream> instead of <iostream.h> in Example Code for PCH
  docs/build/creating-precompiled-header-files.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1673 TCP port forwarding
  docs/linux/media/port_forwading_copy_error.PNG
  docs/linux/media/port_forwarding_headers_error.PNG
Labels: do-not-merge, review-team-triage

#1674 Give linux media standardized filenames
  docs/linux/media/port-forwarding-copy-error.png
  docs/linux/media/port-forwarding-headers-error.png
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1659 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-c4335.md
  docs/error-messages/compiler-warnings/compiler-warning-c4355.md
  docs/error-messages/compiler-warnings/compiler-warning-c4368.md
  docs/error-messages/compiler-warnings/compiler-warning-c4394.md
  docs/error-messages/compiler-warnings/compiler-warning-c4430.md
  docs/error-messages/compiler-warnings/compiler-warning-c4439.md
  docs/error-messages/compiler-warnings/compiler-warning-c4484.md
  docs/error-messages/compiler-warnings/compiler-warning-c4485.md
  docs/error-messages/compiler-warnings/compiler-warning-c4867.md
  docs/error-messages/compiler-warnings/compiler-warning-c4972.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-and-level-4-c4949.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4002.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4003.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4005.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4006.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4010.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4020.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4028.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4033.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4036.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1660 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4042.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4047.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4052.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4068.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4074.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4075.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4077.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4079.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4080.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4081.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4083.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4085.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4086.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4087.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4090.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4091.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4096.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4097.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4103.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4109.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1661 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4114.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4117.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4129.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4138.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4141.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4142.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4144.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4145.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4154.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4155.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4162.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4163.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4167.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4172.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4174.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4176.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4177.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4178.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4180.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4183.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1662 Add language identifiers
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4185.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4186.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4215.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4216.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4218.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4224.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4227.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4228.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4229.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4230.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4237.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4258.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4269.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4272.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4273.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4286.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4288.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4291.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4293.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4297.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1675 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/build/reference/cumulative-dependencies.md
  docs/build/reference/dependency-side-effects.md
  docs/build/reference/description-blocks.md
  docs/build/reference/dumpbin-options.md
  docs/build/reference/inferred-dependents.md
  docs/build/reference/multiple-targets.md
  docs/build/reference/nopdb.md
  docs/build/reference/pseudotargets.md
  docs/build/reference/running-nmake.md
  docs/build/reference/search-paths-for-dependents.md
  docs/build/reference/targets-in-multiple-description-blocks.md
  docs/build/reference/targets.md
  docs/toc.yml
Labels: do-not-merge

#1672 PG0165 can also be shown when PGD is readonly
  docs/error-messages/tool-errors/profile-guided-optimization-error-pg0165.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1524 Improve example for signal function
  docs/c-runtime-library/reference/signal.md
Labels: Change sent to author, assessing_(C&L), do-not-merge
