Repository MicrosoftDocs/cpp-docs, pull requests merged in 2020-01, with the labels that each got.

#1822 Update using-cpp-interop-implicit-pinvoke.md
  docs/dotnet/using-cpp-interop-implicit-pinvoke.md
Labels: do-not-merge, review-team-triage

#1825 Update windows-runtime-cpp-template-library-wrl.md
  docs/cppcx/wrl/windows-runtime-cpp-template-library-wrl.md
Labels: do-not-merge, review-team-triage

#1829 Fix git push error for protected CLA branch
  docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md
Labels: do-not-merge

#1808 Corrected the func definition for vector emplace
  docs/standard-library/vector-class.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1823 Updated topic to account for 64-bit Windows
  docs/mfc/reference/ctreectrl-class.md
Labels: do-not-merge, review-team-triage

#1834 Fix git push error for protected CLA branch
  docs/atl-mfc-shared/reference/cfiletimespan-class.md
  docs/c-runtime-library/reference/ismbblead-ismbblead-l.md
  docs/c-runtime-library/reference/mbclen-mblen-mblen-l.md
  docs/c-runtime-library/reference/strerror-strerror-wcserror-wcserror.md
Labels: do-not-merge

#1838 Fix git push error for protected CLA branch
  docs/build/vcpkg.md
  docs/cpp/welcome-back-to-cpp-modern-cpp.md
Labels: do-not-merge

#1840 `clang` -> `Clang`
  docs/build/clang-support-msbuild.md
Labels: do-not-merge, review-team-triage

#1845 Add new properties for Linux IntelliSense
  docs/linux/prop-pages/general-linux.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1844 Update Linux IntelliSense behavior
  docs/linux/configure-a-linux-project.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1847 Minor wording change
  docs/build/configure-cmake-debugging-sessions.md
Labels: do-not-merge, review-team-triage

#1856 Add link to CMake specific documentation
  docs/build/launch-vs-schema-reference-cpp.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1865 16.5 update
  docs/build/cmakesettings-reference.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#1867 Add a missing underscore
  docs/cpp/m128i.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#1872 multiple files: fix typos
  docs/atl-mfc-shared/reference/crect-class.md
  docs/atl/reference/ccomapartment-class.md
  docs/atl/reference/ccomsafedeletecriticalsection-class.md
  docs/atl/reference/codesnippet/CPP/catlservicemodulet-class_1.cpp
  docs/atl/reference/codesnippet/CPP/catlservicemodulet-class_2.cpp
  docs/c-runtime-library/floating-point-support.md
  docs/c-runtime-library/reference/alloca.md
  docs/c-runtime-library/reference/write.md
  docs/cppcx/enums-c-cx.md
  docs/cppcx/wrl/agileeventsource-class.md
  docs/cppcx/wrl/argtraits-structure.md
  docs/cppcx/wrl/callback-function-wrl.md
  docs/cppcx/wrl/eventsource-class.md
  docs/cppcx/wrl/handlet-class.md
  docs/cppcx/wrl/implements-structure.md
  docs/extensions/explicit-overrides-cpp-component-extensions.md
  docs/mfc/codesnippet/CPP/ccmdtarget-class_1.cpp
  docs/mfc/codesnippet/CPP/cevent-class_2.cpp
  docs/mfc/codesnippet/CPP/colelinkingdoc-class_1.h
  docs/mfc/codesnippet/CPP/colesafearray-class_4.cpp
  docs/mfc/reference/codesnippet/CPP/application-information-and-management_8.cpp
  docs/mfc/reference/codesnippet/CPP/ctreectrl-class_1.cpp
  docs/mfc/reference/codesnippet/CPP/cwnd-class_56.cpp
  docs/mfc/walkthrough-creating-a-ribbon-application-by-using-mfc.md
  docs/parallel/concrt/reference/concurrency-namespace-functions.md
  docs/parallel/concrt/reference/concurrency-namespace-operators.md
  docs/parallel/concrt/reference/concurrency-namespace.md
  docs/porting/visual-cpp-change-history-2003-2015.md
  docs/preprocessor/pointers-to-members.md
  docs/standard-library/algorithm-functions.md
  docs/standard-library/basic-string-class.md
  docs/standard-library/basic-string-view-class.md
  docs/standard-library/logical-and-struct.md
Labels: Change sent to author, cpp-cx/tech, do-not-merge, visual-cpp/prod

#1870 Fix git push error for protected CLA branch
  docs/build/reference/dependentloadflag.md
  docs/porting/modifying-winver-and-win32-winnt.md
  docs/porting/upgrading-projects-from-earlier-versions-of-visual-cpp.md
  docs/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application.md
Labels: do-not-merge

#1885 Update setlocale locale string description
  docs/c-runtime-library/reference/setlocale-wsetlocale.md
Labels: Change sent to author, assessing_(C&L), cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#1887 Fix git push error for protected CLA branch
  docs/c-runtime-library/reference/popen-wpopen.md
  docs/standard-library/initializer-list-class.md
Labels: do-not-merge
