Repository MicrosoftDocs/cpp-docs, pull requests merged in 2020-08, with the labels that each got.

#2340 Update loop.md
  docs/preprocessor/loop.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2341 Fix git push error for protected CLA branch
  docs/build/reference/cgthreads-code-generation-threads.md
  docs/build/reference/compiler-options-listed-alphabetically.md
  docs/build/reference/compiler-options-listed-by-category.md
  docs/build/reference/guard-enable-eh-continuation-metadata.md
  docs/build/reference/permissive-standards-conformance.md
  docs/build/reference/rtc-run-time-error-checks.md
  docs/build/reference/sourcedependencies.md
  docs/build/reference/x-ignore-standard-include-paths.md
  docs/build/reference/yu-use-precompiled-header-file.md
  docs/build/toc.yml
  docs/c-language/c-keywords.md
  docs/c-language/data-type-specifiers-and-equivalents.md
  docs/cpp/bitwise-exclusive-or-operator-hat.md
  docs/cpp/bstr-t-assign.md
  docs/cpp/cpp-type-system-modern-cpp.md
  docs/cpp/declspec.md
  docs/cpp/for-statement-cpp.md
  docs/error-messages/compiler-errors-2/compiler-error-c3386.md
  docs/error-messages/compiler-errors-2/compiler-error-c3389.md
  docs/mfc/reference/colecontrol-class.md
  docs/mfc/reference/coledispatchdriver-class.md
  docs/parallel/openmp/1-introduction.md
  docs/standard-library/allocator-class.md
  docs/standard-library/domain-error-class.md
  docs/standard-library/hash-map-class.md
  docs/standard-library/hash-multimap-class.md
  docs/standard-library/invalid-argument-class.md
  docs/standard-library/length-error-class.md
  docs/standard-library/logic-error-class.md
  docs/standard-library/moneypunct-class.md
  docs/standard-library/numeric-limits-class.md
  docs/standard-library/out-of-range-class.md
  docs/standard-library/overflow-error-class.md
  docs/standard-library/pair-structure.md
  docs/standard-library/runtime-error-class.md
  docs/standard-library/unary-function-struct.md
  docs/standard-library/underflow-error-class.md
  docs/windows/attributes/custom-cpp.md
Labels: do-not-merge

#2347 Fix git push error for protected CLA branch
  docs/cpp/arrays-cpp.md
  docs/overview/visual-cpp-help-and-community.md
  docs/standard-library/charconv-functions.md
  docs/standard-library/chars-format-class.md
Labels: do-not-merge

#2344 Fix syntax examples for interfaces, ref classes, and ref structs (C++/CLI and C++/CX)
  docs/extensions/classes-and-structs-cpp-component-extensions.md
  docs/extensions/interface-class-cpp-component-extensions.md
Labels: Change sent to author, aq-pr-triaged, cpp-cli/tech, do-not-merge, visual-cpp/prod

#2351 Update iterators.md
  docs/standard-library/iterators.md
Labels: Change sent to author, aq-pr-triaged, cpp-standard-libraries/tech, do-not-merge, visual-cpp/prod

#2358 Fix git push error for protected CLA branch
  docs/build/media/vs2019-choose-console-app.png
  docs/linux/cmake-linux-configure.md
  docs/linux/cmake-linux-project.md
  docs/linux/configure-a-linux-project.md
  docs/linux/create-a-new-linux-project.md
  docs/linux/deploy-run-and-debug-your-linux-project.md
  docs/linux/toc.yml
  docs/overview/visual-cpp-language-conformance.md
Labels: do-not-merge

#2348 Add C Runtime UTF-8 support documentation
  docs/c-runtime-library/locale-names-languages-and-country-region-strings.md
  docs/c-runtime-library/reference/setlocale-wsetlocale.md
  docs/c-runtime-library/reference/setmbcp.md
Labels: Change sent to author, aq-pr-triaged, cpp-ucrt/tech, ready-to-merge, visual-cpp/prod

#2360 Repo sync for protected CLA branch
  docs/overview/visual-cpp-language-conformance.md
Labels: CLA, Change sent to author, cpp-language/tech, visual-cpp/prod

#2361 Update C26474 to clarify base/derived use cases.
  docs/code-quality/c26474.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2364 Repo sync for protected CLA branch
  docs/atl/reference/aggregation-and-class-factory-macros.md
  docs/build/reference/advanced-property-page.md
  docs/code-quality/c26474.md
  docs/overview/what-s-new-for-visual-cpp-in-visual-studio.md
Labels: CLA, Change sent to author, cpp-ide/tech, visual-cpp/prod

#2368 line break in see also
  docs/build/reference/creating-a-makefile-project.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2370 Add C++ Core Guidelines link on C26405
  docs/code-quality/c26405.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2387 Add C++ Core Guidelines link to C26427
  docs/code-quality/c26427.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2366 Update msbuild-visual-cpp-overview.md
  docs/build/reference/msbuild-visual-cpp-overview.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2375 C26498 - Description & Examples
  docs/code-quality/c26498.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2376 Add C++ Core Guidelines link to C26406
  docs/code-quality/c26406.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2389 Delete extra ]
  docs/build/reference/std-specify-language-standard-version.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2379 Add C++CoreGuidelines link to C26407
  docs/code-quality/c26407.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2391 Repo sync for protected CLA branch
  docs/cppcx/collections-c-cx.md
  docs/cppcx/platform-array-class.md
  docs/cppcx/platform-collections-map-class.md
  docs/cppcx/platform-collections-mapview-class.md
  docs/intrinsics/x64-amd64-intrinsics-list.md
  docs/intrinsics/x86-intrinsics-list.md
Labels: CLA, Change sent to author, cpp-cx/tech, do-not-merge, visual-cpp/prod

#2380 Add C++ Core Guidelines links to C26410
  docs/code-quality/c26410.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2381 Add C++ Core Guidelines link to C26411
  docs/code-quality/c26411.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2404 Add example for C26402
  docs/code-quality/c26402.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2402 Repo sync for protected CLA branch
  docs/_breadcrumb/toc.yml
  docs/c-runtime-library/format-specification-fields-scanf-and-wscanf-functions.md
  docs/linux/cmake-linux-configure.md
  docs/linux/toc.yml
Labels: CLA, Change sent to author, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#2403 Add example for C26409
  docs/code-quality/c26409.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2419 Repo sync for protected CLA branch
  docs/build-insights/tutorials/vcperf-and-wpa.md
  docs/build/building-on-the-command-line.md
  docs/build/how-to-integrate-custom-tools-into-the-project-properties.md
  docs/build/modify-project-properties-without-changing-project-file.md
  docs/build/reference/driver-windows-nt-kernel-mode-driver.md
  docs/build/reference/dynamicbase-use-address-space-layout-randomization.md
  docs/build/reference/dynamicbase.md
  docs/build/reference/highentropyva-support-64-bit-aslr.md
  docs/build/reference/highentropyva.md
  docs/build/reference/qpar-auto-parallelizer.md
  docs/build/reference/qpar-report-auto-parallelizer-reporting-level.md
  docs/build/reference/qvec-report-auto-vectorizer-reporting-level.md
  docs/build/reference/return-value-of-cl-exe.md
  docs/build/reference/tsaware-create-terminal-server-aware-application.md
  docs/build/reference/vcpp-directories-property-page.md
  docs/build/walkthrough-compiling-a-cpp-cx-program-on-the-command-line.md
  docs/c-runtime-library/country-region-strings.md
  docs/c-runtime-library/global-state.md
  docs/c-runtime-library/language-strings.md
  docs/c-runtime-library/locale-names-languages-and-country-region-strings.md
  docs/c-runtime-library/outp-outpw-outpd.md
  docs/code-quality/using-rule-sets-to-specify-the-cpp-rules-to-run.md
  docs/cpp/constructors-cpp.md
  docs/cppcx/wrl/ftmbase-class.md
  docs/cppcx/wrl/windows-runtime-cpp-template-library-wrl.md
  docs/data/data-access-in-cpp.md
  docs/index.yml
  docs/mfc/mfc-internet-programming-basics.md
  docs/mfc/ole-background.md
  docs/mfc/reference/casyncsocket-class.md
  docs/mfc/walkthrough-updating-the-mfc-scribble-application-part-1.md
  docs/overview/cpp-conformance-improvements.md
  docs/overview/game-development-cpp.md
  docs/overview/visual-cpp-help-and-community.md
  docs/overview/visual-cpp-samples.md
  docs/parallel/concrt/concurrency-runtime.md
  docs/porting/porting-from-unix-to-win32.md
  docs/security/developer-guidance-speculative-execution.md
Labels: CLA, Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2414 Fix arm64 abi return value docs
  docs/build/arm64-windows-abi-conventions.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2420 Repo sync for protected CLA branch
  docs/build/exception-handling-x64.md
  docs/build/reference/eh-exception-handling-model.md
  docs/c-language/summary-of-statements.md
  docs/c-language/try-except-statement-c.md
  docs/c-language/try-finally-statement-c.md
  docs/cloud/cloud-and-web-programming-in-visual-cpp.md
  docs/code-quality/c6242.md
  docs/cpp/cleaning-up-resources.md
  docs/cpp/errors-and-exception-handling-modern-cpp.md
  docs/cpp/mixing-c-structured-and-cpp-exceptions.md
  docs/cpp/restrictions-on-exception-handlers.md
  docs/cpp/restrictions-on-termination-handlers.md
  docs/cpp/structured-exception-handling-c-cpp.md
  docs/cpp/timing-of-exception-handling-a-summary.md
  docs/cpp/try-except-statement.md
  docs/cpp/try-finally-statement.md
  docs/dotnet/exceptions-in-cpp-cli.md
  docs/dotnet/how-to-catch-exceptions-in-native-code-thrown-from-msil.md
  docs/error-messages/compiler-errors-2/compiler-error-c2702.md
  docs/error-messages/compiler-errors-2/compiler-error-c2703.md
  docs/error-messages/compiler-errors-2/compiler-error-c2705.md
  docs/error-messages/compiler-errors-2/compiler-error-c2706.md
  docs/error-messages/compiler-errors-2/compiler-error-c2712.md
  docs/error-messages/compiler-errors-2/compiler-error-c2713.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4571.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4932.md
Labels: CLA, Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2423 Repo sync for protected CLA branch
  docs/atl-mfc-shared/reference/coledatetime-class.md
  docs/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l.md
  docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md
  docs/code-quality/c26447.md
  docs/mfc/reference/ccombobox-class.md
  docs/mfc/reference/cobarray-class.md
Labels: CLA, Change sent to author, cpp-mfc/tech, do-not-merge, visual-cpp/prod
