Repository MicrosoftDocs/cpp-docs, pull requests merged in 2020-02, with the labels that each got.

#1893 Add extra F1 keyword to C++ Command Line article
  docs/build/reference/command-line-property-pages.md
Labels: Change sent to author, assessing_(C&L), cpp-tools/tech, do-not-merge, visual-cpp/prod

#1899 Fix git push error for protected CLA branch
  docs/build/reference/compiler-options-listed-alphabetically.md
  docs/build/reference/compiler-options-listed-by-category.md
  docs/build/reference/q-options-low-level-operations.md
  docs/build/reference/qspectre-load-cf.md
  docs/build/reference/qspectre-load.md
  docs/toc.yml
Labels: do-not-merge

#1733 Fix wrong path to the MathLibrary.lib file
  docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md
Labels: Change sent to author, assessing_(C&L), cpp-tools/tech, do-not-merge, visual-cpp/prod

#1905 Update /wholearchive command documentation to be more like other comm…
  docs/build/reference/wholearchive-include-all-library-object-files.md
Labels: Change sent to author, assessing_(C&L), cpp-tools/tech, do-not-merge, visual-cpp/prod

#1911 Recommend Docs Authoring Pack extension and configure dev langs
  .vscode/extensions.json
  .vscode/settings.json
Labels: do-not-merge, review-team-triage

#1920 Fix git push error for protected CLA branch
  docs/c-runtime-library/reference/create-locale-wcreate-locale.md
  docs/c-runtime-library/reference/setlocale-wsetlocale.md
  docs/c-runtime-library/reference/setmbcp.md
Labels: do-not-merge

#1913 Update invoke-result-class.md
  docs/standard-library/invoke-result-class.md
Labels: Change sent to author, assessing_(C&L), cpp-standard-libraries/tech, ready-to-merge, visual-cpp/prod

#1914 Fix typos
  docs/build/arm64-exception-handling.md
Labels: Change sent to author, assessing_(C&L), cpp-tools/tech, do-not-merge, visual-cpp/prod

#1922 Add new _MSC_VER values to the table.
  docs/preprocessor/predefined-macros.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#1928 Fix CWnd::FromHandlePermanent description
  docs/mfc/reference/cwnd-class.md
Labels: Change sent to author, assessing_(C&L), cpp-mfc/tech, ready-to-merge, visual-cpp/prod

#1932 Document new rule C26817
  docs/code-quality/c26817.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#1937 Fixed typo
  docs/build/cmakesettings-reference.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#1940 Fix git push error for protected CLA branch
  docs/code-quality/toc.yml
Labels: do-not-merge

#1945 Fix git push error for protected CLA branch
  docs/build/reference/general-property-page-project.md
  docs/build/reference/msbuild-visual-cpp-overview.md
  docs/cross-platform/android-debugger-prop-page.md
  docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md
  docs/cross-platform/clang-android-prop-page.md
  docs/cross-platform/clanglink-prop-page.md
  docs/cross-platform/create-an-android-native-activity-app.md
  docs/cross-platform/cross-platform-mobile-development-examples.md
  docs/cross-platform/cross-platform-prop-pages.md
  docs/cross-platform/general-android-prop-page.md
  docs/cross-platform/general-makefile-android-prop-page.md
  docs/cross-platform/import-an-xcode-project.md
  docs/cross-platform/index.md
  docs/cross-platform/install-and-configure-tools-to-build-using-ios.md
  docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md
  docs/cross-platform/media/cppmdd-common-vcremote.png
  docs/cross-platform/media/cppmdd-emulator-running-app.png
  docs/cross-platform/media/cppmdd-newproject.png
  docs/cross-platform/media/cppmdd-opengles-andbuild.png
  docs/cross-platform/media/cppmdd-opengles-andemulator.png
  docs/cross-platform/media/cppmdd-opengles-andoutput.png
  docs/cross-platform/media/cppmdd-opengles-contextswitcher.png
  docs/cross-platform/media/cppmdd-opengles-iosbuild.png
  docs/cross-platform/media/cppmdd-opengles-iosdebug.png
  docs/cross-platform/media/cppmdd-opengles-iosdevelopmentteam.png
  docs/cross-platform/media/cppmdd-opengles-iosdevice.png
  docs/cross-platform/media/cppmdd-opengles-iosxcodeid.png
  docs/cross-platform/media/cppmdd-opengles-iosxcodesign.png
  docs/cross-platform/media/cppmdd-opengles-iosxcodeteam.png
  docs/cross-platform/media/cppmdd-opengles-newproj.png
  docs/cross-platform/media/cppmdd-opengles-pickemulator.png
  docs/cross-platform/media/cppmdd-opengles-pickplatformarm64.png
  docs/cross-platform/media/cppmdd-opengles-solexpl.png
  docs/cross-platform/media/cppmdd-opengles-solutionplat.png
  docs/cross-platform/media/cppmdd-options-android.png
  docs/cross-platform/media/cppmdd-options-ios.png
  docs/cross-platform/media/cppmdd-rc-na-solution-x86.png
  docs/cross-platform/media/cppmdd-rc-na-solutionexp.png
  docs/cross-platform/media/cppmdd-u2-importxcode-browse.png
  docs/cross-platform/media/cppmdd-u2-importxcode-choose.png
  docs/cross-platform/media/cppmdd-u2-importxcode-destination.jpg
  docs/cross-platform/media/cppmdd-u2-importxcode-frameworks.jpg
  docs/cross-platform/media/cppmdd-u2-importxcode-global.jpg
  docs/cross-platform/media/cppmdd-u2-importxcode-library.jpg
  docs/cross-platform/media/cppmdd-u2-importxcode-projects.jpg
  docs/cross-platform/media/cppmdd-u2-remotemachine-menu.jpg
  docs/cross-platform/media/cppmdd-u2-remotemachine-output.png
  docs/cross-platform/media/cppmdd-vcremote-generateclientcert.png
  docs/cross-platform/nmake-android-prop-page.md
  docs/cross-platform/sync-changes-between-xcode-and-visual-studio.md
  docs/cross-platform/toc.yml
  docs/cross-platform/visual-cpp-for-cross-platform-mobile-development.md
  docs/docfx.json
  docs/preprocessor/float-control.md
  docs/toc.yml
Labels: do-not-merge

#1946 Fixed formatting
  docs/mfc/reference/cchecklistbox-class.md
Labels: do-not-merge
