Repository MicrosoftDocs/cpp-docs, pull requests merged in 2020-04, with the labels that each got.

#2049 Remove mention of gdbserver
  docs/build/configure-cmake-debugging-sessions.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2055 Fix Module Class Macros table
  docs/cppcx/wrl/module-class.md
Labels: Change sent to author, cpp-cx/tech, do-not-merge, visual-cpp/prod

#2056 Fix push_back prototypes
  docs/standard-library/list-class.md
Labels: Change sent to author, aq-pr-triaged, cpp-standard-libraries/tech, do-not-merge, visual-cpp/prod

#2058 Fix git push error for protected CLA branch
  docs/build/configure-cmake-debugging-sessions.md
  docs/cpp/raw-pointers.md
Labels: do-not-merge

#2061 Fix git push error for protected CLA branch
  docs/cpp/try-except-statement.md
Labels: do-not-merge

#2046 (Probably) a typo about `locale_t` text
  docs/c-runtime-library/standard-types.md
Labels: Change sent to author, aq-pr-triaged, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#2062 Add legacy_stdio_float_rounding.obj
  docs/c-runtime-library/link-options.md
Labels: Change sent to author, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#2089 Update welcome-back-to-cpp-modern-cpp.md
  docs/cpp/welcome-back-to-cpp-modern-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2092 Update header-files-cpp.md
  docs/cpp/header-files-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2098 Fix git push error for protected CLA branch
  docs/build/configure-cmake-debugging-sessions.md
  docs/build/media/cmake-targets-add-debug-configuration.png
  docs/build/media/cmake-targets-add-debug.png
  docs/build/reference/permissive-standards-conformance.md
  docs/build/walkthrough-creating-and-using-a-static-library-cpp.md
  docs/cpp/for-statement-cpp.md
  docs/toc.yml
  docs/windows/codesnippet/CPP/walkthrough-creating-and-using-a-static-library-cpp_1.h
  docs/windows/codesnippet/CPP/walkthrough-creating-and-using-a-static-library-cpp_2.cpp
  docs/windows/codesnippet/CPP/walkthrough-creating-and-using-a-static-library-cpp_3.cpp
Labels: do-not-merge

#2103 Fix git push error for protected CLA branch
  docs/c-language/range-of-char-values.md
  docs/c-language/truncation-of-floating-point-values.md
  docs/c-language/values.md
  docs/cpp/switch-statement-cpp.md
  docs/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps.md
Labels: do-not-merge

#2106 Proper formatting in code-block
  docs/cpp/trivial-standard-layout-and-pod-types.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2112 fix: c-runtime-library/global-state.md
  docs/c-runtime-library/global-state.md
Labels: Change sent to author, aq-pr-triaged, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#2115 Rename Box member function to more appropriately describe the function's behavior
  docs/cpp/constructors-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2124 Fix git push error for protected CLA branch
  docs/atl/reference/cpatht-class.md
  docs/c-language/calls-with-a-variable-number-of-arguments.md
  docs/c-language/parameters.md
  docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md
  docs/cpp/anonymous-class-types.md
  docs/cpp/ellipses-and-variadic-templates.md
  docs/cpp/postfix-expressions.md
  docs/cpp/raw-pointers.md
  docs/cpp/sizeof-operator.md
  docs/cpp/templates-cpp.md
  docs/cppcx/array-and-writeonlyarray-c-cx.md
  docs/cppcx/attributes-c-cx.md
  docs/cppcx/collections-c-cx.md
  docs/cppcx/delegates-c-cx.md
  docs/cppcx/interfaces-c-cx.md
  docs/cppcx/obtaining-pointers-to-data-buffers-c-cx.md
  docs/cppcx/platform-collections-map-class.md
  docs/cppcx/platform-collections-mapview-class.md
  docs/cppcx/platform-collections-namespace.md
  docs/cppcx/platform-collections-unorderedmap-class.md
  docs/cppcx/platform-collections-unorderedmapview-class.md
  docs/cppcx/platform-collections-vector-class.md
  docs/cppcx/platform-collections-vectorview-class.md
  docs/cppcx/platform-guid-value-class.md
  docs/cppcx/threading-and-marshaling-c-cx.md
  docs/cppcx/wrl/deferrableeventargs-class.md
  docs/cppcx/wrl/walkthrough-creating-a-windows-store-app-using-wrl-and-media-foundation.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4251.md
  docs/extensions/variable-argument-lists-dot-dot-dot-cpp-cli.md
  docs/mfc/reference/styles-used-by-mfc.md
  docs/parallel/concrt/creating-asynchronous-operations-in-cpp-for-windows-store-apps.md
  docs/parallel/concrt/walkthrough-connecting-using-tasks-and-xml-http-requests.md
  docs/standard-library/integer-sequence-class.md
  docs/toc.yml
Labels: do-not-merge

#2126 Fix git push error for protected CLA branch
  docs/code-quality/c6054.md
Labels: do-not-merge

#2129 Fix git push error for protected CLA branch
  docs/code-quality/c26818.md
  docs/code-quality/c26819.md
  docs/code-quality/toc.yml
Labels: do-not-merge

#2137 Fix git push error for protected CLA branch
  docs/atl/changing-the-drawing-code-atl-tutorial-part-4.md
  docs/atl/messagehandler.md
  docs/atl/reference/aggregation-and-class-factory-macros.md
  docs/atl/reference/atl-base-module70-structure.md
  docs/atl/reference/atl-com-module70-structure.md
  docs/atl/reference/atl-drawinfo-structure.md
  docs/atl/reference/atl-func-info-structure.md
  docs/atl/reference/atl-http-utility-functions.md
  docs/atl/reference/atl-module70-structure.md
  docs/atl/reference/atl-operators.md
  docs/atl/reference/atl-path-functions.md
  docs/atl/reference/atl-text-encoding-functions.md
  docs/atl/reference/atl-typedefs.md
  docs/atl/reference/atl-url-scheme-enum.md
  docs/atl/reference/atl-win-module70-structure.md
  docs/atl/reference/atlcreatewnddata-structure.md
  docs/atl/reference/ca2aex-class.md
  docs/atl/reference/ca2caex-class.md
  docs/atl/reference/ca2wex-class.md
  docs/atl/reference/caccesstoken-class.md
  docs/atl/reference/cacl-class.md
  docs/atl/reference/cadapt-class.md
  docs/atl/reference/category-macros.md
  docs/atl/reference/catlarray-class.md
  docs/atl/reference/catlautothreadmodule-class.md
  docs/atl/reference/catlautothreadmodulet-class.md
  docs/atl/reference/catlbasemodule-class.md
  docs/atl/reference/catlcommodule-class.md
  docs/atl/reference/catldebuginterfacesmodule-class.md
  docs/atl/reference/catldllmodulet-class.md
  docs/atl/reference/catlexception-class.md
  docs/atl/reference/catlexemodulet-class.md
  docs/atl/reference/catlfile-class.md
  docs/atl/reference/catlfilemapping-class.md
  docs/atl/reference/catlfilemappingbase-class.md
  docs/atl/reference/catllist-class.md
  docs/atl/reference/catlmap-class.md
  docs/atl/reference/catlmodule-class.md
  docs/atl/reference/catlmodulet-class.md
  docs/atl/reference/catlpreviewctrlimpl-class.md
  docs/atl/reference/catlservicemodulet-class.md
  docs/atl/reference/catltemporaryfile-class.md
  docs/atl/reference/catltransactionmanager-class.md
  docs/atl/reference/catlwinmodule-class.md
  docs/atl/reference/cautoptr-class.md
  docs/atl/reference/cautoptrarray-class.md
  docs/atl/registry-scripting-examples.md
  docs/atl/understanding-backus-naur-form-bnf-syntax.md
  docs/atl/understanding-parse-trees.md
  docs/atl/using-replaceable-parameters-the-registrar-s-preprocessor.md
  docs/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8.md
  docs/c-language/switch-statement-c.md
Labels: do-not-merge

#2141 Typo "** _O_APPEND**"→"**_O_APPEND**"
  docs/c-runtime-library/reference/fopen-s-wfopen-s.md
Labels: Change sent to author, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#2147 Fix git push error for protected CLA branch
  docs/data/data-access-in-cpp.md
  docs/get-started/breadcrumb/toc.yml
  docs/parallel/amp/cpp-amp-overview.md
  docs/parallel/auto-parallelization-and-auto-vectorization.md
  docs/parallel/concrt/concurrency-runtime.md
Labels: do-not-merge

#2142 Update tsaware-create-terminal-server-aware-application.md
  docs/build/reference/tsaware-create-terminal-server-aware-application.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2149 Fix git push error for protected CLA branch
  docs/c-language/switch-statement-c.md
  docs/cpp/switch-statement-cpp.md
Labels: do-not-merge

#2152 Fix git push error for protected CLA branch
  docs/code-quality/c26481.md
  docs/code-quality/c26485.md
Labels: do-not-merge

#2143 Fix: typo at fill example (c0 -> v1)
  docs/standard-library/array-class-stl.md
Labels: Change sent to author, aq-pr-triaged, cpp-standard-libraries/tech, do-not-merge, visual-cpp/prod
