Repository MicrosoftDocs/cpp-docs, pull requests merged in 2020-12, with the labels that each got.

#2628 Repo sync for protected CLA branch
  docs/build/configure-cmake-debugging-sessions.md
  docs/build/reference/fa-fa-listing-file.md
  docs/build/using-database-ole-and-sockets-extension-dlls-in-regular-dlls.md
  docs/c-runtime-library/reference/div.md
  docs/mfc/reference/extension-dll-macros.md
  docs/mfc/tn033-dll-version-of-mfc.md
Labels: CLA, Change sent to author, cpp-tools/tech, visual-cpp/prod

#2629 Repo sync for protected CLA branch
  docs/c-runtime-library/reference/mbsnbcat-s-mbsnbcat-s-l.md
Labels: CLA, Change sent to author, cpp-ucrt/tech, visual-cpp/prod

#2640 Repo sync for protected CLA branch
  docs/atl-mfc-shared/reference/cstringt-class.md
  docs/cpp/scope-resolution-operator.md
Labels: CLA, Change sent to author, cpp-mfc/tech, visual-cpp/prod

#2641 Update vcpkg.md
  docs/build/vcpkg.md
Labels: Change sent to author, aq-pr-triaged, cpp-ide/tech, do-not-merge, visual-cpp/prod

#2643 Repo sync for protected CLA branch
  docs/build/configure-cmake-debugging-sessions.md
Labels: CLA, Change sent to author, cpp-tools/tech, visual-cpp/prod

#2646 Repo sync for protected CLA branch
  docs/cpp/program-termination.md
  docs/dotnet/dotnet-programming-with-cpp-cli-visual-cpp.md
  docs/dotnet/how-to-create-clr-console-applications-cpp-cli.md
  docs/mfc/mfc-application-architecture-classes.md
Labels: CLA, Change sent to author, cpp-cli/tech, visual-cpp/prod

#2655 Repo sync for protected CLA branch
  docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md
  docs/c-language/alignment-c.md
  docs/c-language/c-keywords.md
  docs/c-language/toc.yml
  docs/c-runtime-library/tgmath.md
Labels: CLA, Change sent to author, cpp-c-language/tech, visual-cpp/prod

#2650 Clarify behavior of C26401 for delete this idiom
  docs/code-quality/c26401.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2651 Clarify behavior of C26409 for delete this idiom
  docs/code-quality/c26409.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2659 Repo sync for protected CLA branch
  docs/build/reference/compiler-options-listed-alphabetically.md
  docs/build/reference/compiler-options-listed-by-category.md
  docs/build/reference/compiler-options.md
  docs/preprocessor/predefined-macros.md
  docs/preprocessor/variadic-macros.md
Labels: CLA, Change sent to author, cpp-tools/tech, visual-cpp/prod

#2512 Added info about nItem parameter of SetItemState.
  docs/mfc/reference/clistctrl-class.md
Labels: Change sent to author, aq-pr-triaged, cpp-mfc/tech, do-not-merge, visual-cpp/prod

#2668 Repo sync for protected CLA branch
  docs/build/configure-cmake-debugging-sessions.md
  docs/c-runtime-library/format-specification-fields-scanf-and-wscanf-functions.md
  docs/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume.md
  docs/code-quality/toc.yml
  docs/code-quality/using-the-cpp-core-guidelines-checkers.md
  docs/cpp/main-function-command-line-args.md
  docs/cpp/writing-an-exception-filter.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4027.md
  docs/intrinsics/noop.md
  docs/linux/connect-to-your-remote-linux-computer.md
Labels: CLA, Change sent to author, cpp-tools/tech, visual-cpp/prod
