Repository MicrosoftDocs/cpp-docs, pull requests merged in 2020-05, with the labels that each got.

#2158 Update pack.md
  docs/preprocessor/pack.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2159 Fix git push error for protected CLA branch
  docs/build/importing-function-calls-using-declspec-dllimport.md
  docs/cpp/switch-statement-cpp.md
  docs/linux/cmake-linux-project.md
  docs/linux/download-install-and-setup-the-linux-development-workload.md
Labels: do-not-merge

#2181 minor grammar fix
  docs/cpp/scope-visual-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2189 Fix git push error for protected CLA branch
  docs/cpp/switch-statement-cpp.md
Labels: do-not-merge

#2193 Fixed location in IDE
  docs/build/reference/md-mt-ld-use-run-time-library.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2194 Minor standardization
  docs/cpp/keywords-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2196 Update move-constructors-and-move-assignment-operators-cpp.md
  docs/cpp/move-constructors-and-move-assignment-operators-cpp.md
Labels: do-not-merge

#2197 Update move-constructors-and-move-assignment-operators-cpp.md
  docs/cpp/move-constructors-and-move-assignment-operators-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2202 Fix git push error for protected CLA branch
  docs/build/vscpp-step-0-installation.md
  docs/cpp/welcome-back-to-cpp-modern-cpp.md
Labels: do-not-merge

#2203 Fix typo in c5045.md
  docs/error-messages/compiler-warnings/c5045.md
Labels: Change sent to author, cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#2205 Fix git push error for protected CLA branch
  docs/build/configure-cmake-debugging-sessions.md
  docs/overview/cpp-conformance-improvements.md
  docs/overview/visual-cpp-language-conformance.md
  docs/overview/what-s-new-for-visual-cpp-in-visual-studio.md
Labels: do-not-merge

#2213 Fix git push error for protected CLA branch
  docs/build-insights/get-started-with-cpp-build-insights.md
  docs/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l.md
Labels: do-not-merge

#2210 RFG feature was replaced by PAC and the associated arithmetic ops were never impl…
  docs/build/arm64-exception-handling.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2216 Fix git push error for protected CLA branch
  docs/cpp/thiscall.md
Labels: do-not-merge

#2221 Fix a typo
  docs/cpp/program-and-linkage-cpp.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#2222 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/code-quality/index.yml
  docs/code-quality/toc.yml
  docs/cpp/index.yml
  docs/cpp/toc.yml
  docs/linux/index.md
  docs/linux/index.yml
  docs/linux/toc.yml
  docs/overview/visual-cpp-in-visual-studio.md
Labels: do-not-merge

#2226 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/atl-mfc-shared/reference/TOC.md
  docs/atl-mfc-shared/toc.yml
  docs/build-insights/index.yml
  docs/build-insights/toc.yml
  docs/c-language/index.yml
  docs/c-language/toc.yml
  docs/c-runtime-library/toc.yml
  docs/cross-platform/index.md
  docs/cross-platform/index.yml
  docs/cross-platform/toc.yml
Labels: do-not-merge

#2232 Fix git push error for protected CLA branch
  docs/assembler/masm/processor-manufacturer-programming-manuals.md
  docs/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s.md
  docs/cpp/data-type-ranges.md
  docs/ide/writing-and-refactoring-code-cpp.md
  docs/media/index/logo-asm.svg
  docs/media/index/logo-atl.svg
  docs/media/index/logo-mfc.svg
  docs/mfc/reference/cftpfilefind-class.md
  docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md
Labels: do-not-merge

#2230 Whitespace at cpp/pointers-to-members.md
  docs/cpp/pointers-to-members.md
Labels: Change sent to author, aq-pr-triaged, cpp-language/tech, do-not-merge, visual-cpp/prod

#2235 Fix typo
  docs/parallel/thread-local-storage-tls.md
Labels: Change sent to author, cpp-parallel/tech, do-not-merge, visual-cpp/prod

#2233 Fix git push error for protected CLA branch
  docs/standard-library/cpp-standard-library-header-files.md
  docs/standard-library/span-class.md
  docs/standard-library/span-functions.md
  docs/standard-library/span.md
  docs/standard-library/toc.yml
Labels: do-not-merge
