Repository MicrosoftDocs/cpp-docs, pull requests merged in 2020-06, with the labels that each got.

#2241 Add 19041 printf behavior changes
  docs/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l.md
Labels: Change sent to author, aq-pr-triaged, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#2244 Fix git push error for protected CLA branch
  docs/build/reference/cetcompat.md
  docs/build/reference/compiler-options-listed-alphabetically.md
  docs/build/reference/compiler-options-listed-by-category.md
  docs/build/reference/guard-enable-eh-continuation-metadata.md
  docs/build/toc.yml
Labels: do-not-merge

#2246 Fix misnamed function name: fesetenv -> fesetround
  docs/c-runtime-library/link-options.md
  docs/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l.md
Labels: Change sent to author, aq-pr-triaged, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#2250 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/_breadcrumb/toc.yml
  docs/assembler/toc.yml
  docs/build/reference/permissive-standards-conformance.md
  docs/build/reference/std-specify-language-standard-version.md
  docs/build/reference/zc-noexcepttypes.md
  docs/c-runtime-library/reference/atan-atanf-atanl-atan2-atan2f-atan2l.md
  docs/c-runtime-library/reference/ceil-ceilf-ceill.md
  docs/c-runtime-library/reference/cos-cosf-cosl.md
  docs/c-runtime-library/reference/floor-floorf-floorl.md
  docs/c-runtime-library/reference/log-logf-log10-log10f.md
  docs/c-runtime-library/reference/sin-sinf-sinl.md
  docs/c-runtime-library/reference/sqrt-sqrtf-sqrtl.md
  docs/code-quality/index.yml
  docs/code-quality/toc.yml
  docs/index.md
  docs/index.yml
  docs/intrinsics/index.yml
  docs/intrinsics/toc.yml
  docs/overview/toc.yml
Labels: do-not-merge

#2261 Update details on data files
  docs/build/profile-guided-optimizations.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#2259 Fix git push error for protected CLA branch
  docs/c-language/return-statement-c.md
Labels: do-not-merge

#1976 Function-call evaluation is context-dependent
  docs/cpp/function-call-operator-parens.md
Labels: Change sent to author, aq-pr-triaged, cpp-language/tech, do-not-merge, visual-cpp/prod

#2269 Fix git push error for protected CLA branch
  docs/build/cmakesettings-reference.md
Labels: do-not-merge

#2268 Add information about ruleset schema
  docs/code-quality/using-rule-sets-to-specify-the-cpp-rules-to-run.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, ready-to-merge, visual-cpp/prod

#2277 Fix git push error for protected CLA branch
  docs/code-quality/using-rule-sets-to-specify-the-cpp-rules-to-run.md
  docs/linux/cmake-linux-project.md
  docs/linux/configure-a-linux-project.md
Labels: do-not-merge

#1996 Disable failing rules for CI enablement
  .markdownlint.json
Labels: aq-pr-triaged, cpp/svc, do-not-merge, review-team-triage

#2263 Meaning of the postfix-expression
  docs/cpp/function-call-operator-parens.md
Labels: Change sent to author, aq-pr-triaged, cpp-language/tech, do-not-merge, visual-cpp/prod

#2284 Update clock.md
  docs/c-runtime-library/reference/clock.md
Labels: Change sent to author, aq-pr-triaged, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#2285 Fix git push error for protected CLA branch
  docs/atl/reference/atl-wizards-and-dialog-boxes.md
  docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md
  docs/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l.md
  docs/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l.md
  docs/mfc/reference/casyncsocket-class.md
  docs/mfc/reference/cmdiframewndex-class.md
  docs/mfc/reference/cmultidoctemplate-class.md
  docs/safeint/safeint-class.md
  docs/standard-library/basic-filebuf-class.md
  docs/standard-library/error-category-class.md
  docs/windows/redistributing-visual-cpp-files.md
Labels: do-not-merge
