Repository MicrosoftDocs/cpp-docs, pull requests merged in 2021-05, with the labels that each got.

#3117 Update experimental-module.md
  docs/build/reference/experimental-module.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#3119 Repo sync for protected CLA branch
  docs/c-runtime-library/reference/splitpath-s-wsplitpath-s.md
  docs/code-quality/c6290.md
  docs/cppcx/partial-classes-c-cx.md
  docs/error-messages/compiler-errors-1/compiler-error-c2139.md
  docs/error-messages/compiler-errors-1/compiler-error-c2201.md
  docs/error-messages/compiler-errors-2/compiler-error-c2668.md
  docs/error-messages/compiler-errors-2/compiler-error-c7536.md
  docs/error-messages/compiler-errors-2/compiler-errors-c7500-through-c7999.md
  docs/error-messages/compiler-warnings/c4597.md
  docs/error-messages/compiler-warnings/c4768.md
  docs/error-messages/compiler-warnings/c4841.md
  docs/error-messages/compiler-warnings/c4843.md
  docs/error-messages/compiler-warnings/c5038.md
  docs/error-messages/compiler-warnings/c5050.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4179.md
  docs/error-messages/compiler-warnings/compiler-warning-level-4-c4189.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4400-through-c4599.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4600-through-c4799.md
  docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md
  docs/error-messages/toc.yml
  docs/mfc/reference/casyncsocket-class.md
  docs/overview/cpp-conformance-improvements-2017.md
  docs/overview/visual-cpp-samples.md
  docs/porting/porting-guide-mfc-scribble.md
  docs/preprocessor/compiler-warnings-that-are-off-by-default.md
  docs/standard-library/chrono-functions.md
  docs/standard-library/chrono-literals.md
  docs/standard-library/chrono-operators.md
  docs/standard-library/chrono.md
  docs/standard-library/day-class.md
  docs/standard-library/hhmmss-class.md
  docs/standard-library/leap-second-class.md
  docs/standard-library/leap-second-info-struct.md
  docs/standard-library/month-class.md
  docs/standard-library/regular-expressions-cpp.md
  docs/standard-library/span-class.md
  docs/standard-library/time-zone-class.md
  docs/standard-library/toc.yml
  docs/standard-library/weekday-class.md
  docs/standard-library/weekdayindexed-class.md
  docs/standard-library/weekdaylast-class.md
  docs/standard-library/year-class.md
Labels: CLA, Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod

#3120 Repo sync for protected CLA branch
  docs/standard-library/chrono-functions.md
  docs/standard-library/chrono.md
  docs/standard-library/leap-second-class.md
  docs/standard-library/leap-second-info-struct.md
  docs/standard-library/month-class.md
  docs/standard-library/time-zone-class.md
  docs/standard-library/weekday-class.md
  docs/standard-library/weekdayindexed-class.md
  docs/standard-library/weekdaylast-class.md
  docs/standard-library/year-class.md
Labels: CLA, Change sent to author, cpp-standard-libraries/tech, visual-cpp/prod

#3121 Update fopen-s-wfopen-s.md
  docs/c-runtime-library/reference/fopen-s-wfopen-s.md
Labels: Change sent to author, aq-pr-triaged, cpp-ucrt/tech, do-not-merge, visual-cpp/prod

#3125 Repo sync for protected CLA branch
  docs/build/cmake-presets-vs.md
  docs/c-runtime-library/reference/beginthread-beginthreadex.md
  docs/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l.md
  docs/c-runtime-library/reference/signal.md
  docs/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l.md
  docs/c-runtime-library/reference/strcmp-wcscmp-mbscmp.md
  docs/c-runtime-library/reference/strcpy-wcscpy-mbscpy.md
  docs/c-runtime-library/reference/stricmp-wcsicmp-mbsicmp-stricmp-l-wcsicmp-l-mbsicmp-l.md
  docs/c-runtime-library/reference/strlen-wcslen-mbslen-mbslen-l-mbstrlen-mbstrlen-l.md
  docs/c-runtime-library/reference/strstr-wcsstr-mbsstr-mbsstr-l.md
  docs/c-runtime-library/reference/time-time32-time64.md
  docs/standard-library/ranges.md
Labels: CLA, Change sent to author, cpp-ucrt/tech, visual-cpp/prod

#3129 Repo sync for protected CLA branch
  .openpublishing.redirection.json
  docs/build/adding-references-in-visual-cpp-projects.md
  docs/build/cmake-projects-in-visual-studio.md
  docs/build/creating-and-managing-visual-cpp-projects.md
  docs/build/install-vcpkg.md
  docs/build/integrate-vcpkg.md
  docs/build/manage-libraries-with-vcpkg.md
  docs/build/toc.yml
  docs/build/vcpkg-command-line-reference.md
  docs/build/vcpkg.md
  docs/code-quality/using-the-cpp-core-guidelines-checkers.md
  docs/error-messages/compiler-errors-1/fatal-error-c1083.md
  docs/error-messages/tool-errors/linker-tools-error-lnk1104.md
  docs/error-messages/tool-errors/linker-tools-error-lnk2019.md
  docs/error-messages/tool-errors/linker-tools-error-lnk2038.md
  docs/overview/libraries-cpp.md
  docs/overview/overview-of-cpp-development.md
  docs/overview/visual-cpp-in-visual-studio.md
  docs/overview/what-s-new-for-cpp-2017.md
  docs/porting/porting-third-party-libraries.md
  docs/standard-library/month-class.md
  docs/standard-library/weekday-class.md
  docs/windows/overview-of-windows-programming-in-cpp.md
Labels: CLA, Change sent to author, cpp-ide/tech, visual-cpp/prod

#3130 It's showed as C++ on docs.microsoft.com and is confusing.
  docs/sanitizers/error-global-buffer-overflow.md
Labels: Change sent to author, cpp-tools/tech, do-not-merge, visual-cpp/prod

#3137 Repo sync for protected CLA branch
  docs/build/reference/compiler-options-listed-alphabetically.md
  docs/build/reference/compiler-options-listed-by-category.md
  docs/build/reference/external-external-headers-diagnostics.md
  docs/build/toc.yml
Labels: CLA, Change sent to author, cpp-tools/tech, visual-cpp/prod

#3143 Repo sync for protected CLA branch
  docs/overview/visual-cpp-language-conformance.md
Labels: CLA, Change sent to author, cpp-language/tech, visual-cpp/prod

#3128 extraneous named parameters on deleted functions
  docs/code-quality/c26432.md
Labels: Change sent to author, aq-pr-triaged, cpp-tools/tech, do-not-merge, visual-cpp/prod

#3144 Repo sync for protected CLA branch
  docs/build/reference/module-exportheader.md
  docs/build/walkthrough-header-units.md
Labels: CLA, Change sent to author, cpp-tools/tech, visual-cpp/prod

#3146 Repo sync for protected CLA branch
  docs/build/reference/analyze-code-analysis.md
  docs/error-messages/compiler-errors-2/compiler-error-c3779.md
  docs/error-messages/compiler-errors-2/compiler-errors-c3500-through-c3999.md
  docs/error-messages/toc.yml
Labels: CLA, Change sent to author, cpp-diagnostics/tech, visual-cpp/prod

#3162 Repo sync for protected CLA branch
  docs/build/reference/analyze-code-analysis.md
Labels: CLA, Change sent to author, cpp-tools/tech, visual-cpp/prod

#3163 Repo sync for protected CLA branch
  docs/c-runtime-library/reference/aligned-malloc.md
  docs/c-runtime-library/reference/countof-macro.md
  docs/c-runtime-library/reference/crt-alphabetical-function-reference.md
  docs/c-runtime-library/reference/fscanf-s-fscanf-s-l-fwscanf-s-fwscanf-s-l.md
  docs/c-runtime-library/reference/fseek-fseeki64.md
  docs/c-runtime-library/reference/fwrite.md
  docs/c-runtime-library/reference/itoa-s-itow-s.md
  docs/c-runtime-library/reference/kbhit.md
  docs/c-runtime-library/reference/localtime-localtime32-localtime64.md
  docs/c-runtime-library/reference/mbstowcs-s-mbstowcs-s-l.md
  docs/c-runtime-library/reference/scanf-scanf-l-wscanf-wscanf-l.md
  docs/c-runtime-library/reference/setmode.md
  docs/c-runtime-library/reference/splitpath-wsplitpath.md
  docs/c-runtime-library/reference/sscanf-sscanf-l-swscanf-swscanf-l.md
  docs/c-runtime-library/reference/strchr-wcschr-mbschr-mbschr-l.md
  docs/c-runtime-library/reference/strncpy-strncpy-l-wcsncpy-wcsncpy-l-mbsncpy-mbsncpy-l.md
  docs/c-runtime-library/reference/va-arg-va-copy-va-end-va-start.md
  docs/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l.md
  docs/c-runtime-library/reference/wcstombs-s-wcstombs-s-l.md
  docs/c-runtime-library/stdin-stdout-stderr.md
Labels: CLA, Change sent to author, cpp-ucrt/tech, visual-cpp/prod

#3168 enhancement / typo
  docs/standard-library/algorithm-functions.md
Labels: Change sent to author, aq-pr-triaged, cpp-standard-libraries/tech, do-not-merge, visual-cpp/prod

#3169 Update compiler-warning-level-1-c4103.md
  docs/error-messages/compiler-warnings/compiler-warning-level-1-c4103.md
Labels: Change sent to author, cpp-diagnostics/tech, do-not-merge, visual-cpp/prod

#3170 Fix grammatical error
  docs/cpp/lambda-expression-syntax.md
Labels: Change sent to author, cpp-language/tech, do-not-merge, visual-cpp/prod
