Repository MicrosoftDocs/cpp-docs, pull requests merged in 2022-07, with the labels that each got.

#4018 Repo sync for protected CLA branch
  docs/build/reference/arch-arm.md
  docs/build/reference/arch-arm64.md
  docs/build/reference/arch-minimum-cpu-architecture.md
  docs/build/reference/arch-x64.md
  docs/build/reference/arch-x86.md
  docs/build/reference/c-cpp-prop-page.md
  docs/build/toc.yml
  docs/cpp/aliases-and-typedefs-cpp.md
  docs/cpp/cast-operator-parens.md
  docs/cpp/class-templates.md
  docs/cpp/enumerations-cpp.md
  docs/cpp/friend-cpp.md
  docs/cpp/source-code-organization-cpp-templates.md
  docs/dotnet/how-to-define-and-consume-enums-in-cpp-cli.md
  docs/dotnet/how-to-marshal-arrays-using-pinvoke.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, aq-pr-triaged, cpp-tools/tech, CLA

#4019 Repo sync for protected CLA branch
  docs/cpp/class-member-overview.md
  docs/intrinsics/bitscanreverse-bitscanreverse64.md
  docs/intrinsics/x64-amd64-intrinsics-list.md
  docs/intrinsics/x86-intrinsics-list.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, cpp-tools/tech, CLA, needs-human-review

#4023 Add the default /Zp setting for ARM64EC.
  docs/build/reference/zp-struct-member-alignment.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, cpp-tools/tech, qualifies-for-auto-merge

#4025 Make the struct packing for ARM64EC more clear
  docs/build/arm64ec-windows-abi-conventions.md
Labels: Change sent to author, ready-to-merge, visual-cpp/prod, aq-pr-triaged, cpp-tools/tech, qualifies-for-auto-merge

#4031 Update algorithm-functions.md
  docs/standard-library/algorithm-functions.md
Labels: Change sent to author, ready-to-merge, visual-cpp/prod, cpp-standard-libraries/tech, qualifies-for-auto-merge

#4032 Repo sync for protected CLA branch
  docs/build/reference/std-specify-language-standard-version.md
  docs/c-runtime-library/reference/abort.md
  docs/c-runtime-library/reference/set-abort-behavior.md
  docs/cpp/program-termination.md
  docs/linux/set-up-fips-compliant-secure-remote-linux-development.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, cpp-ucrt/tech, CLA, needs-human-review

#4026 Update pack.md
  docs/preprocessor/pack.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, cpp-language/tech, aq-pr-triaged, qualifies-for-auto-merge

#4034 Repo sync for protected CLA branch
  docs/build/cmake-presets-vs.md
  docs/build/reference/std-specify-language-standard-version.md
  docs/build/walkthrough-build-debug-wsl2.md
  docs/preprocessor/predefined-macros.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, aq-pr-triaged, cpp-tools/tech, CLA, qualifies-for-auto-merge

#4039 Repo sync for protected CLA branch
  docs/cpp/overloading-unary-operators.md
  docs/standard-library/algorithm-functions.md
  docs/standard-library/vector.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, cpp-standard-libraries/tech, CLA, needs-human-review

#4037 Update cpen-class.md
  docs/mfc/reference/cpen-class.md
Labels: Change sent to author, ready-to-merge, visual-cpp/prod, review-team-triage, aq-pr-triaged, cpp-mfc/tech, qualifies-for-auto-merge

#4041 Repo sync for protected CLA branch
  docs/error-messages/compiler-errors-1/fatal-error-c1020.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, cpp-diagnostics/tech, CLA

#3995 Update tn035-using-multiple-resource-files-and-header-files-with-visu…
  docs/mfc/tn035-using-multiple-resource-files-and-header-files-with-visual-cpp.md
Labels: Change sent to author, ready-to-merge, visual-cpp/prod, aq-pr-triaged, cpp-mfc/tech, qualifies-for-auto-merge

#4059 Repo sync for protected CLA branch
  styleguide/template.md
Labels: do-not-merge, review-team-triage, CLA

#4060 crtsetdbgflag.md: _CrtCheckMemory is not called by default
  docs/c-runtime-library/reference/crtsetdbgflag.md
Labels: Change sent to author, ready-to-merge, visual-cpp/prod, aq-pr-triaged, cpp-ucrt/tech, qualifies-for-auto-merge

#4061 Repo sync for protected CLA branch
  docs/embedded/download-and-install-the-embedded-tooling.md
  docs/embedded/index.yml
  docs/embedded/media/embedded-tools-extension.png
  docs/embedded/media/extensions-pane.png
  docs/embedded/media/linux-and-embedded-workload.png
  docs/embedded/media/peripheral-viewer-vscode.png
  docs/embedded/media/peripheral-viewer.png
  docs/embedded/media/rtos-threads-vscode.png
  docs/embedded/media/rtos-threads.png
  docs/embedded/media/serial-monitor-extension.png
  docs/embedded/media/serial-monitor-vscode.png
  docs/embedded/media/serial-monitor.png
  docs/embedded/media/windows-search-vscode.png
  docs/embedded/peripheral-view.md
  docs/embedded/rtos-view.md
  docs/embedded/serial-monitor.md
  docs/embedded/toc.yml
  docs/index.yml
Labels: do-not-merge, Change sent to author, aq-pr-triaged, CLA

#4071 Update ios-functions.md fix typo
  docs/standard-library/ios-functions.md
Labels: Change sent to author, ready-to-merge, visual-cpp/prod, aq-pr-triaged, cpp-standard-libraries/tech, qualifies-for-auto-merge

#4065 Resolve syncing conflicts from FromPrivateLiveToMaster to main
  docs/c-runtime-library/reference/crtsetdbgflag.md
Labels: do-not-merge, Change sent to author, visual-cpp/prod, review-team-triage, aq-pr-triaged, cpp-ucrt/tech, needs-human-review
