Repository MicrosoftDocs/cpp-docs, pull requests merged in 2024-05, with the labels that each got.

#5037 Clarify that _O_TEXT is ANSI.
  docs/c-runtime-library/reference/open-osfhandle.md
  docs/c-runtime-library/reference/open-wopen.md
  docs/c-runtime-library/reference/pipe.md
  docs/c-runtime-library/reference/setmode.md
  docs/c-runtime-library/reference/sopen-s-wsopen-s.md
  docs/c-runtime-library/reference/sopen-wsopen.md
  docs/c-runtime-library/text-and-binary-mode-file-i-o.md
  docs/c-runtime-library/translation-mode-constants.md
Labels: do-not-merge, Change sent to author, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, ucrt/subsvc

#5035 Remove extra double quote
  docs/build/launch-vs-schema-reference-cpp.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, tools/subsvc

#5038 Updated integritycheck documentation to point to Trusted Signing Service
  docs/build/reference/integritycheck-require-signature-check.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, tools/subsvc

#5033 Update clang-tidy.md
  docs/code-quality/clang-tidy.md
Labels: do-not-merge, Change sent to author, aq-pr-triaged, visual-cpp/svc, tools/subsvc

#5041 Document that `__fastfail` is `noreturn`
  docs/intrinsics/fastfail.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, tools/subsvc
