Repository MicrosoftDocs/cpp-docs, pull requests merged in 2024-02, with the labels that each got.

#4922 Update execution-charset-set-execution-character-set.md
  docs/build/reference/execution-charset-set-execution-character-set.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, tools/subsvc

#4926 Updated the linter settings image.
  docs/ide/media/linter-settings.png
Labels: do-not-merge, review-team-triage, aq-pr-triaged, needs-human-review

#4928 Fix typo
  docs/safeint/safeint-class.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, standard-libraries/subsvc

#4658 largeaddressaware:no is not recommended for 64-bit apps
  docs/build/reference/largeaddressaware-handle-large-addresses.md
Labels: Change sent to author, ready-to-merge, visual-cpp/prod, aq-pr-triaged, cpp-tools/tech, qualifies-for-auto-merge

#4918 Update connect-to-your-remote-linux-computer.md
  docs/linux/connect-to-your-remote-linux-computer.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, linux-development/subsvc

#4945 fixing syntax error in example pragma message.
  docs/preprocessor/message.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, cpp-lang/subsvc

#4957 Correct JSON output of sourcedependencies.md
  docs/build/reference/sourcedependencies.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, tools/subsvc

#4956 Remove DST notes from gmtime docs
  docs/c-runtime-library/reference/gmtime-gmtime32-gmtime64.md
  docs/c-runtime-library/reference/gmtime-s-gmtime32-s-gmtime64-s.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, ucrt/subsvc

#4955 Update assignment-operators.md
  docs/cpp/assignment-operators.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, visual-cpp/svc, cpp-lang/subsvc

#4948 Update clang-tidy.md
  docs/code-quality/clang-tidy.md
Labels: do-not-merge, Change sent to author, aq-pr-triaged, needs-human-review, visual-cpp/svc, tools/subsvc

#4960 Fix built-in operators toc yml
  docs/cpp/left-shift-and-right-shift-operators-input-and-output.md
  docs/cpp/subscript-operator.md
  docs/cpp/toc.yml
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, needs-human-review, visual-cpp/svc, cpp-lang/subsvc
